import {Routes} from '@angular/router';
import * as components from '../components';
import {RoleGuard} from '../guards';
import {hms} from '../constants';

export const RouteSecure: Routes = [
  {path: '', pathMatch: 'full', redirectTo: hms.defaultRoute},
  {
    path: 'dashboard',
    component: components.OrdersComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Read'}],
  },
  {
    path: 'dashboard/approve-orders/:netSuiteOrderId',
    component: components.ScaMyAccountComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Approve'}],
  },
  {
    path: 'dashboard/cancel-orders/:netSuiteOrderId',
    component: components.ScaMyAccountComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Update'}],
  },
  {
    path: 'dispatch',
    component: components.DispatchComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Dispatch', access: 'Read'}],
  },
  {
    path: 'dispatch/assign',
    component: components.DispatchAssignComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Dispatch', access: 'Create'}],
  },
  {
    path: 'dispatch/order/:orderId',
    component: components.DispatchOrderDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Dispatch', access: 'Read'}],
  },
  {
    path: 'dispatch/fulfill-order/:orderId',
    component: components.DispatchFulfillOrderComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Fulfill'}],
  },
  {
    path: 'drivers',
    component: components.DriversComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Driver', access: 'Read'}],
  },
  {
    path: 'drivers/add',
    component: components.DriverAddEditComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Driver', access: 'Create'}],
  },
  {
    path: 'drivers/edit/:driverId',
    component: components.DriverAddEditComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Driver', access: 'Update'}],
  },
  {
    path: 'finance',
    component: components.FinanceComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Finance', access: 'Read'}],
  },
  {
    path: 'hospice',
    component: components.HospicesComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Read'}],
  },
  {
    path: 'hospice/:hospiceId/contract/:contractId/items',
    component: components.ContractItemsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Update'}],
  },
  {
    path: 'hospice/:hospiceId',
    component: components.HospiceDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Read'}],
  },
  {
    path: 'hospice/detail/:hospiceId',
    component: components.HospiceDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Read'}],
  },
  {
    path: 'hospice/:hospiceId/members/add',
    component: components.AddEditHospiceMemberComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Create'}],
  },
  {
    path: 'hospice/:hospiceId/members/import',
    component: components.ImportHospiceMembersComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Create'}],
  },
  {
    path: 'hospice/:hospiceId/settings/members/mappings',
    component: components.HospiceMemberMappingsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Create'}],
  },
  {
    path: 'hospice/:hospiceId/members/edit/:memberId',
    component: components.AddEditHospiceMemberComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Update'}],
  },
  {
    path: 'hospice/:hospiceId/facilities/add',
    component: components.AddEditFacilityComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Facility', access: 'Create'}],
  },
  {
    path: 'hospice/:hospiceId/facilities/import',
    component: components.ImportHospiceFacilityComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Facility', access: 'Create'}],
  },
  {
    path: 'hospice/:hospiceId/facilities/edit/:facilityId',
    component: components.AddEditFacilityComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Facility', access: 'Update'}],
  },
  {
    path: 'hospice/:hospiceId/manage-approvers',
    component: components.ScaMyAccountComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Hospice', access: 'Update'}],
  },
  {
    path: 'inventory',
    component: components.InventoryComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Read'}],
  },
  {
    path: 'inventory/add',
    component: components.AddEditInventoryComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Create'}],
  },
  {
    path: 'inventory/edit/:inventoryId',
    component: components.AddEditInventoryComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Update'}],
  },
  {
    path: 'inventory/logs/:itemId',
    component: components.TransferAuditLogComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Read'}],
  },
  {
    path: 'inventory/logs/:itemId/log/:logId',
    component: components.TransferAuditDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Read'}],
  },
  {
    path: 'inventory/item/:itemId/addons',
    component: components.AddOnConfigComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Update'}],
  },
  {
    path: 'inventory/item/category/info/:categoryId',
    component: components.ItemCategoryDetailsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Update'}],
  },
  {
    path: 'orders/create/:orderType/:patientUniqueId',
    component: components.OrderHmsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Create'}],
  },
  {
    path: 'orders/edit/:orderType/:patientUniqueId/:orderId',
    component: components.OrderHmsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Orders', access: 'Update'}],
  },
  {
    path: 'patients',
    component: components.PatientsComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Patient', access: 'Read'}],
  },
  {
    path: 'patients/add',
    component: components.PatientAddEditComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Patient', access: 'Create'}],
  },
  {
    path: 'patients/edit/:patientId',
    component: components.PatientAddEditComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Patient', access: 'Update'}],
  },
  {
    path: 'profile',
    component: components.ProfileComponent,
  },
  {
    path: 'sites',
    component: components.SitesComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Site', access: 'Read'}],
  },
  {
    path: 'sites/info/:siteId',
    component: components.SiteDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Site', access: 'Read'}],
  },
  {
    path: 'sites/info/:siteId/inventory-transfer',
    component: components.TransferInventoryComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Inventory', access: 'Update'}],
  },
  {
    path: 'sites/info/:siteId/members/add',
    component: components.AddEditSiteMemberComponent,
    canActivate: [RoleGuard],
    data: [
      {name: 'Site', access: 'Create'},
      {name: 'User', access: 'Create'},
    ],
  },
  {
    path: 'sites/info/:siteId/members/edit/:memberId',
    component: components.AddEditSiteMemberComponent,
    canActivate: [RoleGuard],
    data: [
      {name: 'Site', access: 'Update'},
      {name: 'User', access: 'Update'},
    ],
  },
  {
    path: 'system',
    component: components.SystemComponent,
    canActivate: [RoleGuard],
    data: [{name: 'System', access: 'Read'}],
  },
  {
    path: 'users',
    component: components.UsersComponent,
    canActivate: [RoleGuard],
    data: [{name: 'User', access: 'Read'}],
  },
  {
    path: 'users/add',
    component: components.AddUserComponent,
    canActivate: [RoleGuard],
    data: [{name: 'User', access: 'Create'}],
  },
  {
    path: 'users/edit/:userId',
    component: components.UserDetailComponent,
    canActivate: [RoleGuard],
    data: [{name: 'User', access: 'Update'}],
  },
  {
    path: 'vehicles',
    component: components.VehiclesComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Vehicle', access: 'Read'}],
  },
  {
    path: 'report',
    component: components.ReportPortalComponent,
    canActivate: [RoleGuard],
    data: [{name: 'Metrics', access: 'Read'}],
  },
];
