CREATE TABLE [core].[Hospices]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(MAX) NULL,
    [NetSuiteCustomerId] INT NULL DEFAULT NULL,
    [AssignedSiteId] INT NULL,
    [AddressId] INT NULL, 
    [PhoneNumberId] INT NULL, 
    [CustomerTypeId] INT NULL, 
    [Hms2Id] INT NULL, 
    [CreatedDateTime] DATETIME2 NOT NULL, 
    [CreatedByUserId] INT NULL   , 
    [UpdatedDateTime] DATETIME2 NOT NULL, 
    [UpdatedByUserId] INT NULL DEFAULT NULL, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [DeletedByUserId] INT NULL, 
    [DeletedDateTime] DATETIME2 NULL, 
    [IsCreditOnHold] BIT NOT NULL DEFAULT 0, 
    [CreditHoldByUserId] INT NULL, 
    [CreditHoldDateTime] DATETIME2 NULL, 
    [CreditHoldNote] VARCHAR(MAX) NULL, 
    [FhirOrganizationId] UNIQUEIDENTIFIER NULL, 
    [NetSuiteContractingCustomerId] INT NULL, 
    CONSTRAINT [FK_Hospices_Users_Created] FOREIGN KEY ([CreatedByUserId]) REFERENCES [core].[Users]([Id]),
    CONSTRAINT [FK_Hospices_Users_Updated] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [core].[Users]([Id]), 
    CONSTRAINT [FK_Hospices_Users_Deleted] FOREIGN KEY ([DeletedByUserId]) REFERENCES [core].[Users]([Id]),
    CONSTRAINT [FK_Hospices_ToSite] FOREIGN KEY ([AssignedSiteId]) REFERENCES [core].[Sites]([Id]), 
    CONSTRAINT [FK_Hospices_Address] FOREIGN KEY ([AddressId]) REFERENCES [core].[Addresses]([Id]),
    CONSTRAINT [FK_Hospices_PhoneNumbers] FOREIGN KEY ([PhoneNumberId]) REFERENCES [core].[PhoneNumbers]([Id]),
    CONSTRAINT [FK_Hospices_ToCustomerTypes] FOREIGN KEY ([CustomerTypeId]) REFERENCES [core].[CustomerTypes]([Id]),
    CONSTRAINT [FK_Hospices_Credit_Hold_By_User] FOREIGN KEY ([CreditHoldByUserId]) REFERENCES [core].[Users]([Id]),
)
