CREATE TABLE [core].[OrderHeaders]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [OrderDateTime] DATETIME2 NOT NULL, 
    [DeliveryAddressId] INT NOT NULL, 
    [PickupAddressId] INT NULL, 
    [OrderRecipientUserId] INT NOT NULL, 
    [HospiceMemberId] INT NULL DEFAULT NULL,
    [HospiceId] INT NULL, 
    [HospiceLocationId] INT NULL, 
    [OrderTypeId] INT NOT NULL DEFAULT 1, 
    [StatusId] INT NOT NULL DEFAULT 10, 
    [DispatchStatusId] INT NULL, 
    [SiteId] INT NULL, 
    [RequestedStartDateTime] DATETIME2 NULL, 
    [RequestedEndDateTime] DATETIME2 NULL, 
    [NetSuiteCustomerId] INT NULL, 
    [NetSuiteCustomerContactId] INT NULL, 
    [NetSuiteOrderId] INT NULL, 
    [PatientUUID] UNIQUEIDENTIFIER NOT NULL,
    [OrderNumber] VARCHAR(MAX) NULL DEFAULT NEXT VALUE FOR [core].[OrderNumberSequence],
    [ConfirmationNumber] VARCHAR(MAX) NULL, 
    [FulfillmentStartDateTime] DATETIME2 NULL,
    [FulfillmentStartAtLatitude] DECIMAL(11, 8) NULL, 
    [FulfillmentStartAtLongitude] DECIMAL(11, 8) NULL,
    [FulfillmentEndDateTime] DATETIME2 NULL, 
    [FulfillmentEndAtLatitude] DECIMAL(11, 8) NULL, 
    [FulfillmentEndAtLongitude] DECIMAL(11, 8) NULL,
    [StatOrder] BIT NULL DEFAULT 0, 
    [CreatedDateTime] DATETIME2 NULL, 
    [CreatedByUserId] INT NULL   , 
    [UpdatedDateTime] DATETIME2 NULL, 
    [UpdatedByUserId] INT NULL ,
    [ExternalOrderNumber] VARCHAR(MAX) NULL, 
    [PickupReason] VARCHAR(MAX) NULL,
    [PartialFulfillmentReason] VARCHAR(MAX) NULL, 
    [IsExceptionFulfillment] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [FK_OrderHeaders_ToAddress_Delivery] FOREIGN KEY ([DeliveryAddressId]) REFERENCES [core].[Addresses]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToAddress_Pickup] FOREIGN KEY ([PickupAddressId]) REFERENCES [core].[Addresses]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToHospices] FOREIGN KEY ([HospiceId]) REFERENCES [core].[Hospices]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToHospiceLocations] FOREIGN KEY ([HospiceLocationId]) REFERENCES [core].[HospiceLocations]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToOrderTypes] FOREIGN KEY ([OrderTypeId]) REFERENCES [core].[OrderTypes]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToOrderStatusTypes] FOREIGN KEY ([StatusId]) REFERENCES [core].[OrderHeaderStatusTypes]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToDispatchStatusTypes] FOREIGN KEY ([DispatchStatusId]) REFERENCES [core].[OrderHeaderStatusTypes]([Id]), 
    CONSTRAINT [FK_OrderHeaders_ToSites] FOREIGN KEY ([SiteId]) REFERENCES [core].[Sites]([Id]),
    CONSTRAINT [FK_OrderHeaders_Users_Created] FOREIGN KEY ([CreatedByUserId]) REFERENCES [core].[Users]([Id]),
    CONSTRAINT [FK_OrderHeaders_Users_Updated] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [core].[Users]([Id]),
    CONSTRAINT [FK_OrderHeaders_HospiceMember] FOREIGN KEY ([HospiceMemberId]) REFERENCES [core].[HospiceMember]([Id]),
)

GO
CREATE SEQUENCE [core].[OrderNumberSequence] start with 1 increment by 1;