CREATE TABLE [core].[OrderLineItems]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [OrderHeaderId] INT NOT NULL,
    [SiteId] INT NULL,
    [DeliveryAddressId] INT NOT NULL,
    [PickupAddressId] INT NULL, 
    [ItemId] INT NULL, 
    [ItemCount] INT NOT NULL DEFAULT 1,  
    [RequestedStartDateTime] DATETIME2 NULL, 
    [RequestedEndDateTime] DATETIME2 NULL,
    [NetSuiteOrderLineItemId] INT NULL, 
    [NetSuiteItemId] INT NULL, 
    [StatusId] INT NULL, 
    [DispatchStatusId] INT NULL, 
    [ActionId] INT NULL,  
    [EquipmentSettings] NVARCHAR(MAX) NULL, 
    [SerialNumber] VARCHAR(MAX) NULL, 
    [AssetTagNumber] VARCHAR(MAX) NULL, 
    [LotNumber] VARCHAR(MAX) NULL, 
    [CreatedDateTime] DATETIME2 NULL, 
    [CreatedByUserId] INT NULL   , 
    [UpdatedDateTime] DATETIME2 NULL, 
    [UpdatedByUserId] INT NULL ,
    [AdditionalField1] DATETIME2 NULL,
    [AdditionalField2] DECIMAL(11, 8) NULL, 
    [AdditionalField3] DECIMAL(11, 8) NULL,
    [AdditionalField4] DATETIME2 NULL, 
    [AdditionalField5] DECIMAL(11, 8) NULL, 
    [AdditionalField6] DECIMAL(11, 8) NULL,
    CONSTRAINT [FK_OrderLineItems_ToOrderHeaders] FOREIGN KEY ([OrderHeaderId]) REFERENCES [core].[OrderHeaders]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_OrderLineItems_ToSites] FOREIGN KEY ([SiteId]) REFERENCES [core].[Sites]([Id]), 
    CONSTRAINT [FK_OrderLineItems_ToAddresses_Delivery] FOREIGN KEY ([DeliveryAddressId]) REFERENCES [core].[Addresses]([Id]),
    CONSTRAINT [FK_OrderLineItems_ToAddresses_Pickup] FOREIGN KEY ([PickupAddressId]) REFERENCES [core].[Addresses]([Id]), 
    CONSTRAINT [FK_OrderLineItems_ToItems] FOREIGN KEY ([ItemId]) REFERENCES [core].[Items]([Id]),
    CONSTRAINT [FK_OrderLineItems_ToOrderLineItemStatusTypes] FOREIGN KEY ([StatusId]) REFERENCES [core].[OrderLineItemStatusTypes]([Id]),
    CONSTRAINT [FK_OrderLineItems_ToOrderLineItemDispatchStatusTypes] FOREIGN KEY ([DispatchStatusId]) REFERENCES [core].[OrderLineItemStatusTypes]([Id]),
    CONSTRAINT [FK_OrderLineItems_ToOrderTypes] FOREIGN KEY ([ActionId]) REFERENCES [core].[OrderTypes]([Id]), 
    CONSTRAINT [FK_OrderLineItems_Users_Created] FOREIGN KEY ([CreatedByUserId]) REFERENCES [core].[Users]([Id]),
    CONSTRAINT [FK_OrderLineItems_Users_Updated] FOREIGN KEY ([UpdatedByUserId]) REFERENCES [core].[Users]([Id]), 
)
