CREATE TABLE [core].[Subscriptions]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(MAX) NULL, 
    [NetSuiteSubscriptionId] INT NULL, 
    [NetSuiteCustomerId] INT NULL, 
    [HospiceId] INT NULL, 
    [NetSuiteBillToCustomerId] INT NULL, 
    [BillToCustomer] VARCHAR(MAX) NULL,
    [NetSuiteBillToEntityId] INT NULL, 
    [BillToEntity] VARCHAR(MAX) NULL,
    [ConsolidateBilling] BIT NULL, 
    [StartDate] DATETIME2 NULL, 
    [EndDate] DATETIME2 NULL, 
    [NetSuiteCurrencyId] INT NULL, 
    [Currency] VARCHAR(MAX) NULL, 
    [NetSuiteBillingProfileId] INT NULL, 
    [BillingProfile] VARCHAR(MAX) NULL, 
    [NetSuiteChargeScheduleId] INT NULL, 
    [ChargeSchedule] VARCHAR(MAX) NULL, 
    [InheritChargeScheduleFromMasterContract] BIT NULL, 
    [NetSuiteRenewalTemplateId] INT NULL, 
    [RenewalTemplate] VARCHAR(MAX) NULL, 
    [NetSuiteEnableLineItemShippingId] INT NULL, 
    [EnableLineItemShipping] VARCHAR(MAX) NULL, 
    [CreatedDateTime] DATETIME2 NULL, 
    [LastModifiedDateTime] DATETIME2 NULL, 
    [NetSuiteLastFetchedDateTime] DATETIME2 NULL,
    [IsInactive] BIT NULL, 
    CONSTRAINT [FK_Subscriptions_ToHospices] FOREIGN KEY ([HospiceId]) REFERENCES [core].[Hospices]([Id])
)
