CREATE TABLE [core].[SubscriptionItems]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(MAX) NULL, 
    [NetSuiteSubscriptionItemId] INT NULL, 
    [SubscriptionId] INT NULL, 
    [NetSuiteSubscriptionId] INT NULL, 
    [NetSuiteCustomerId] INT NULL, 
    [HospiceId] INT NULL, 
    [NetSuiteItemId] INT NULL, 
    [ItemId] INT NULL, 
    [ItemDescription] VARCHAR(MAX) NULL, 
    [NetSuiteRateTypeId] INT NULL, 
    [RateType] VARCHAR(MAX) NULL, 
    [InvertNegativeQuantity] BIT NULL, 
    [UseAlternateTermMultiplier] BIT NULL, 
    [OverageRate] FLOAT NULL, 
    [NetSuiteRatePlanId] INT NULL, 
    [RatePlan] VARCHAR(MAX) NULL, 
    [StartDate] DATETIME2 NULL, 
    [EndDate] DATETIME2 NULL, 
    [BillInArrears] BIT NULL, 
    [RatingScheduleBillInArrears] BIT NULL, 
    [NetSuiteChargeScheduleUsedId] INT NULL, 
    [ChargeScheduleUsed] VARCHAR(MAX) NULL, 
    [NetSuiteCurrencyId] INT NULL, 
    [Currency] VARCHAR(MAX) NULL, 
    [NetSuiteExcludeChargesFromBillingWhenId] INT NULL, 
    [ExcludeChargesFromBillingWhen] VARCHAR(MAX) NULL, 
    [ExcludeFromOrderLevelMinimumCommitment] BIT NULL, 
    [NetSuiteInheritChargeScheduleFromId] INT NULL, 
    [InheritChargeScheduleFrom] VARCHAR(MAX) NULL, 
    [NetSuiteProRationTypeId] INT NULL, 
    [ProRationType] VARCHAR(MAX) NULL, 
    [RatingPriority] INT NULL, 
    [ChargeIncludedUnits] BIT NULL, 
    [CreditRebillPriorNewCountCharges] BIT NULL, 
    [PushFutureCountCharges] BIT NULL, 
    [AdjustmentExcludePriorToEffectiveDate] BIT NULL, 
    [ApplyAdjustmentsRetroactively] BIT NULL, 
    [NetSuiteRenewalItemId] INT NULL, 
    [RenewalItem] VARCHAR(MAX) NULL, 
    [ApplyPrepaidToAllSubscriptionItems] BIT NULL, 
    [CreatedDateTime] DATETIME2 NULL, 
    [LastModifiedDatetime] DATETIME2 NULL, 
    [NetSuiteLastFetchedDateTime] DATETIME2 NULL,
    [IsInactive] BIT NULL, 
    CONSTRAINT [FK_SubscriptionItems_ToSubscriptions] FOREIGN KEY ([SubscriptionId]) REFERENCES [core].[Subscriptions]([Id]), 
    CONSTRAINT [FK_SubscriptionItems_ToHospices] FOREIGN KEY ([HospiceId]) REFERENCES [core].[Hospices]([Id]), 
    CONSTRAINT [FK_SubscriptionItems_ToItems] FOREIGN KEY ([ItemId]) REFERENCES [core].[Items]([Id])
)
