/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

DECLARE @Hms2HmsDigitalList TABLE (HMS2Id INT, HMS2Name VARCHAR(MAX), 
								   NetSuiteCustomerId INT, NetSuiteName VARCHAR(MAX),
								   DigitalHospiceId INT, DigitalHospiceName VARCHAR(MAX), 
								   DigitalHospiceLocationId INT, DigitalHospiceLocationName VARCHAR(MAX), DigitalType VARCHAR(MAX))

INSERT INTO @Hms2HmsDigitalList VALUES
			
			(9,'SS) CIMA - San Antonio, TX',16466,'CIMA - San Antonio, TX',218,'CIMA Hospice',424,'CIMA - San Antonio, TX','Location'),
			(42,'Allstar - Sugar Land, TX',2054,'AllStar - Sugar Land, TX',20,'AllStar Hospice, Inc',28,'AllStar - Sugar Land, TX','Location'),
			(72,'Thee Hospice - Hunstsville, TX',42852,'Thee Hospice - Huntsville, TX',242,'Thee Hospice (dba)',683,'Thee Hospice - Huntsville, TX','Location'),
			(77,'1st Quality - Woodville, TX',2027,'1st Quality - Woodville, TX',6,'1st Quality Hospice, LLC',6,'1st Quality - Woodville, TX','Location'),
			(140,'Thee Hospice - Fairfield, TX',2401,'Thee Hospice - Fairfield, TX',242,'Thee Hospice (dba)',493,'Thee Hospice - Fairfield, TX','Location'),
			(143,'Cuidado Casero - Euless, TX',2156,'Cuidado Casero - Euless, TX',73,'Cuidado Casero Home Health & Hospice',123,'Cuidado Casero - Euless, TX','Location'),
			(151,'Ardent - Flower Mound, TX',2087,'Ardent - Flower Mound, TX',39,'Ardent Hospice, LLC',54,'Ardent - Flower Mound, TX','Location'),
			(152,'CC Young - Dallas, TX',2118,'CC Young - Dallas, TX',58,'CC Young Home Health & Hospice (dba)',91,'CC Young - Dallas, TX','Location'),
			(156,'Silverstone - The Colony, TX',2126,'Silverstone - The Colony, TX',65,'Comfort Care Hospice, LLC (dba) Silverstone Hospice',100,'Silverstone - The Colony, TX','Location'),
			(175,'Hospice Sunset - Clifton, TX',2276,'Hospice Sunset - Clifton, TX',120,'Hospice Sunset (dba)',192,'Hospice Sunset - Clifton, TX','Location'),
			(179,'Cypress Basin - Mt Pleasant, TX',2160,'Cypress Basin - Mt Pleasant, TX',74,'Cypress Basin Hospice, Inc',125,'Cypress Basin - Mt Pleasant, TX','Location'),
			(184,'New Haven - Anaheim, CA',2317,'New Haven - Anaheim, CA',4,'New Haven Hospice Care, Inc',4,'New Haven - Anaheim, CA','Location'),
			(188,'SS) CIMA - El Paso, TX',16239,'CIMA - El Paso, TX',218,'CIMA Hospice',421,'CIMA - El Paso, TX','Location'),
			(195,'PEC - Garden Grove, CA',2339,'PEC - Garden Grove, CA',160,'PEC Hospice (dba)',237,'PEC - Garden Grove, CA','Location'),
			(198,'Compass - Longview, TX',2134,'Compass - Longview, TX',70,'Compass Hospice of East Texas, LLC',118,'Compass - Longview, TX','Location'),
			(199,'Ziba - Lakewood, CA',2430,'Ziba - Lakewood, CA',260,'Ziba Hospice, LLC',530,'Ziba - Lakewood, CA','Location'),
			(200,'Hope International - Torrance, CA',2262,'Hope International - Torrance, CA',112,'Hope International Hospice, Inc',181,'Hope International - Torrance, CA','Location'),
			(203,'St Liz - Los Angeles, CA',2391,'St Liz - Los Angeles, CA',194,'St Liz Hospice, Inc',290,'St Liz - Los Angeles, CA','Location'),
			(205,'Comfort Care - Sherman Oaks, CA',2125,'Comfort Care - Sherman Oaks, CA',64,'Comfort Care Hospice, Inc (CA)',99,'Comfort Care - Sherman Oaks, CA','Location'),
			(208,'LA Hospice - Los Angeles, CA',2294,'LA Hospice - Los Angeles, CA',131,'LA Hospice (dba)',206,'LA Hospice - Los Angeles, CA','Location'),
			(212,'Ivory - Monterey Park, CA',2284,'Ivory - Monterey Park, CA',127,'Ivory Hospice, Inc',202,'Ivory - Monterey Park, CA','Location'),
			(216,'Marshall HomeCare - Marshall, TX',2306,'Marshall HomeCare - Marshall, TX',142,'Marshall HomeCare & Hospice (dba)',217,'Marshall HomeCare - Marshall, TX','Location'),
			(218,'Amara - Edinburg, TX', 2065, 'Amara - Edinburg, TX', 25, 'Amara Hospice (dba)', 38, 'Amara - Edinburg, TX' ,'Location'),
			(224,'Nurses Plus - Cerritos, CA',2324,'Nurses Plus - Cerritos, CA',152,'Nurses Plus Hospice, Inc',227,'Nurses Plus - Cerritos, CA','Location'),
			(229,'SS) CIMA - McAllen (Harlingen), TX',16347,'CIMA - McAllen (Harlingen), TX',218,'CIMA Hospice',422,'CIMA - McAllen (Harlingen), TX','Location'),
			(230,'Allstate - Edinburg, TX', 2055, 'Allstate Hospice, LLC : Allstate - Edinburg, TX', 21, 'Allstate Hospice, LLC', 29, 'Allstate - Edinburg, TX', 'Location'),
			(233,'Cuidado Casero - El Paso, TX',2155,'Cuidado Casero - El Paso, TX',73,'Cuidado Casero Home Health & Hospice',122,'Cuidado Casero - El Paso, TX','Location'),
			(247,'Good Samaritan Society - El Paso, TX',2122,'Good Samaritan Society - El Paso, TX',62,'Good Samaritan HCBS TX, LLC (2)',97,'Good Samaritan Society - El Paso, TX','Location'),
			(248, 'Only Love - McAllen, TX', 2329, 'Only Love Hospice, LLC : Only Love - McAllen, TX', 156, 'Only Love Hospice, LLC', 231, 'Only Love - McAllen, TX', 'Location'),
			(249, 'St Joseph HC - Pharr, TX', 2390, 'St Joseph Hospice Care (dba) : St Joseph HC - Pharr, TX', 193, 'St Joseph Hospice Care (dba)', 289, 'St Joseph HC - Pharr, TX', 'Location'),
			(250,'MaxCare - Westminster, CA',2307,'MaxCare - Westminster, CA',144,'MaxCare Hospice',219,'MaxCare - Westminster, CA','Location'),
			(271,'Gracia - McAllen, TX',2194,'Gracia Hospice Care, LLC : Gracia - McAllen, TX', 97, 'Gracia Hospice Care, LLC', 153, 'Gracia - McAllen, TX', 'Location'),
			(275,'Legacy Home Health - Rio Grande, TX', 2298, 'Legacy Home Health Agency, Inc : Legacy Home Health - Rio Grande, TX', 133, 'Legacy Home Health Agency, Inc', 208, 'Legacy Home Health - Rio Grande, TX', 'Location'),
			(301,'Grace - Los Angeles, CA',2192,'Grace - Los Angeles, CA',96,'Grace Hospice, Inc (CA)',152,'Grace - Los Angeles, CA','Location'),
			(304, 'Hospice Compassionate Care - Mission, TX', 3150, 'Hospice Compassionate Care - Mission, TX', 115, 'Hospice Compassionate Care Services, LLC', 184, 'Hospice Compassionate Care - Mission, TX', 'Lcation'),
			(324,'SS) Compassus - Round Rock, TX',2144,'Compassus - Round Rock, TX',216,'Hospice Compassus, Inc',407,'Compassus - Round Rock, TX','Location'),
			(326,'SS) Compassus - Killeen, TX',2142,'Compassus - Killeen, TX',216,'Hospice Compassus, Inc',405,'Compassus - Killeen, TX','Location'),
			(341,'Ultimate Great Care - Simi Valley, CA',2411,'Ultimate Great Care - Simi Valley, CA',249,'Ultimate Great Care Hospice, Inc',515,'Ultimate Great Care - Simi Valley, CA','Location'),
			(349,'247 - Ontario, CA',2028,'247 - Ontario, CA',7,'247 Hospice (CA)',7,'247 - Ontario, CA','Location'),
			(359,'Hospice of El Paso - El Paso, TX',2273,'Hospice of El Paso - El Paso, TX',117,'Hospice of El Paso, Inc',187,'Hospice of El Paso - El Paso, TX','Location'),
			(372,'Bee First - Harlingen, TX', 2097, 'Bee First Hospice, Inc : Bee First - Harlingen, TX', 50, 'Bee First Hospice, Inc', 79, 'Bee First - Harlingen, TX','Location'),
			(373,'Holy Family - Los Angeles, CA',2248,'Holy Family - Los Angeles, CA',108,'Holy Family Hospice',174,'Holy Family - Los Angeles, CA','Location'),
			(400,'SS) Altus - San Antonio, TX',32721,'Altus - San Antonio, TX (TPA)',311,'Altus Hospice Management, LP',586,'Altus - San Antonio, TX (TPA)','Location'),
			(401,'A-1 - Huntington Beach, CA',2304,'A-1 - Huntington Beach, CA',140,'A-1 Healthcare Management (dba) A-1 Hospice',215,'A-1 - Huntington Beach, CA','Location'),
			(412,'SS) CIMA - New Braunfels, TX',16352,'CIMA - New Braunfels, TX',218,'CIMA Hospice',423,'CIMA - New Braunfels, TX','Location'),
			(415,'Living Waters - New Caney, TX',2300,'Living Waters - New Caney, TX',138,'Living Waters Hospice, Inc',213,'Living Waters - New Caney, TX','Location'),
			(423,'SS) Compassus - Austin (South), TX',2137,'Compassus - Austin (South), TX',216,'Hospice Compassus, Inc',400,'Compassus - Austin (South), TX','Location'),
			(432,'Waterford - Paris, TX',2424,'Waterford - Paris, TX',257,'Waterford Hospice, LLC',527,'Waterford - Paris, TX','Location'),
			(433,'OmegaLife - Houston, TX',2328,'OmegaLife - Houston, TX',155,'OmegaLife Hospice of Texas, Inc',230,'OmegaLife - Houston, TX','Location'),
			(434,'Hospice of El Paso (CCC) - El Paso, TX',2272,'Hospice of El Paso (CCC) - El Paso, TX',117,'Hospice of El Paso, Inc',186,'Hospice of El Paso (CCC) - El Paso, TX','Location'),
			(440,'Faith & Hope - Pasadena, CA',2178,'Faith & Hope - Pasadena, CA',85,'Faith & Hope Hospice Care, Inc',138,'Faith & Hope - Pasadena, CA','Location'),
			(443,'Hospice Care of the Valley - Simi Valley, CA',2269,'Hospice Care of the Valley - Simi Valley, CA',114,'Hospice Care of the Valley, Inc',183,'Hospice Care of the Valley - Simi Valley, CA','Location'),
			(451,'Harbor - San Antonio, TX',3055,'Harbor - San Antonio, TX',101,'Harbor Hospice of Texas',162,'Harbor - San Antonio, TX','Location'),
			(454,'HMS Testing Account',null,null,null,null,null,null,null),
			(456,'Aspen - Lewisville, TX',3751,'Aspen - Lewisville, TX',43,'Aspen Hospice Care, Inc',69,'Aspen - Lewisville, TX','Location'),
			(457,'Total H&PC - Dallas, TX',2404,'Total H&PC - Dallas, TX',243,'Three Oaks Hospice, Inc',494,'Total H&PC - Dallas, TX','Location'),
			(458,'IPH HCS - McAllen, TX', 2283, 'IPH Home Care Services, Inc : IPH HCS - McAllen, TX', 126,'IPH Home Care Services, Inc',201,'IPH HCS - McAllen, TX','Location'),
			(459,'Mar Vista - Burbank, CA',2305,'Mar Vista - Burbank, CA',141,'Mar Vista Hospice, Inc',216,'Mar Vista - Burbank, CA','Location'),
			(460, 'DHR - Edinburg, TX', 2358, 'DHR Health Hospice (dba) : DHR - Edinburg, TX', 78, 'DHR Health Hospice (dba)', 131, 'DHR - Edinburg, TX','Location'),
			(475,'Rejoice - Richardson, TX',2355,'Rejoice - Richardson, TX',1,'Rejoice Hospice, Inc',1,'Rejoice - Richardson, TX','Location'),
			(478,'247 - Orange County, CA',2029,'247 - Orange County, CA',7,'247 Hospice (CA)',698,'247 - Orange County, CA','Location'),
			(483,'HMS DME Testing Hospice',null,null,null,null,null,null,null),
			(488,'Harbor - Lufkin, TX',3053,'Harbor - Lufkin, TX',101,'Harbor Hospice of Texas',161,'Harbor - Lufkin, TX','Location'),
			(489,'Harbor - Jasper (East TX), TX',3052,'Harbor - Jasper (East TX), TX',101,'Harbor Hospice of Texas',160,'Harbor - Jasper (East TX), TX','Location'),
			(493,'Generation Care - Thousand Oaks, CA',3764,'Generation Care - Thousand Oaks, CA',90,'Generation Care, Inc',145,'Generation Care - Thousand Oaks, CA','Location'),
			(501,'Dedicated - Sherman Oaks, CA',2161,'Dedicated - Sherman Oaks, CA',76,'Dedicated Hospice Care, Inc',129,'Dedicated - Sherman Oaks, CA','Location'),
			(502,'Harbor - Livingston, TX',3682,'Harbor - Livingston, TX',101,'Harbor Hospice of Texas',163,'Harbor - Livingston, TX','Location'),
			(517,'Innerjoy - Simi Valley, CA',2278,'Innerjoy - Simi Valley, CA',124,'Innerjoy Hospice Care, Inc',199,'Innerjoy - Simi Valley, CA','Location'),
			(520,'Valley First - Weslaco, TX',2415,'Valley First Hospice Care, LLC : Valley First - Weslaco, TX',253,'Valley First Hospice Care, LLC',520,'Valley First - Weslaco, TX','Location'),
			(521,'Freedom - San Antonio, TX',2183,'Freedom - San Antonio, TX',89,'Freedom Hospice, LLC',144,'Freedom - San Antonio, TX','Location'),
			(523,'Agape H&PC (CA) - Torrance, CA',2049,'Agape H&PC (CA) - Torrance, CA',17,'Agape Hospice & Palliative Care, LLC',25,'Agape H&PC (CA) - Torrance, CA','Location'),
			(526,'Grace-Comfort - Houston, TX',3044,'Grace-Comfort - Houston, TX',251,'US Medical Management, LLC',518,'Grace-Comfort - Houston, TX','Location'),
			(528,'Traditions - Madisonville, TX',3086,'D) Traditions - Madisonville, TX',75,'D) Traditions Hospice (dba)',128,'D) Traditions - Madisonville, TX','Location'),
			(531,'Holding Hands - Dallas, TX',2245,'Holding Hands - Dallas, TX',106,'Holding Hands Hospice',172,'Holding Hands - Dallas, TX','Location'),
			(534,'Angel Care - Henderson, TX',2084,'Angel Care - Henderson, TX',34,'Angel Care Hospice, LLC',48,'Angel Care - Henderson, TX','Location'),
			(540,'Q) Hospice Austin - Austin, TX',2265,'Hospice Austin - Austin, TX',172,'Hospice Austin',251,'Hospice Austin - Austin, TX','Location'),
			(545,'United HCS - Weslaco, TX',2412,'United Hospice Care Services, LLC : United HCS - Weslaco, TX',250,'United HCS & Lynncare HS',517,'United HCS - Weslaco, TX','Location'),
			(546,'Cuidado Casero - Lubbock, TX',2157,'Cuidado Casero - Lubbock, TX',73,'Cuidado Casero Home Health & Hospice',124,'Cuidado Casero - Lubbock, TX','Location'),
			(550,'Hospice in the Pines - Lufkin, TX',2271,'Hospice in the Pines - Lufkin, TX',116,'Hospice in the Pines, Inc',185,'Hospice in the Pines - Lufkin, TX','Location'),
			(552,'SS) Curo : Hospice Plus - Dallas (Central), TX',3429,'Hospice Plus - Dallas (Central), TX',209,'Hospice Plus',359,'Hospice Plus - Dallas (Central), TX','Location'),
			(553,'SS) Curo : Hospice Plus - Terrell, TX',3441,'Hospice Plus - Terrell, TX',209,'Hospice Plus',350,'Hospice Plus - Terrell, TX','Location'),
			(554,'SS) Curo : Hospice Plus - Lewisville, TX',3433,'Hospice Plus - Lewisville, TX',209,'Hospice Plus',356,'Hospice Plus - Lewisville, TX','Location'),
			(555,'SS) Curo : Hospice Plus - Sherman, TX',3439,'Hospice Plus - Sherman, TX',209,'Hospice Plus',352,'Hospice Plus - Sherman, TX','Location'),
			(556,'SS) Curo : Hospice Plus - Greenville, TX',3430,'Hospice Plus - Greenville, TX',209,'Hospice Plus',358,'Hospice Plus - Greenville, TX','Location'),
			(558,'SS) Curo : Hospice Plus - Longview, TX',3434,'Hospice Plus - Longview, TX',209,'Hospice Plus',355,'Hospice Plus - Longview, TX','Location'),
			(559,'SS) Curo : Hospice Plus - The Woodlands, TX',3442,'Hospice Plus - The Woodlands, TX',209,'Hospice Plus',365,'Hospice Plus - The Woodlands, TX','Location'),
			(560,'SS) Curo : Hospice Plus - Bellaire, TX',3424,'Hospice Plus - Bellaire, TX',209,'Hospice Plus',362,'Hospice Plus - Bellaire, TX','Location'),
			(564,'SS) Curo : Hospice Plus - Athens, TX',3422,'Hospice Plus - Athens, TX',209,'Hospice Plus',364,'Hospice Plus - Athens, TX','Location'),
			(568,'SS) Curo : Hospice Plus - Clear Lake (Egret Bay), TX',3426,'Hospice Plus - Clear Lake (Egret Bay), TX',209,'Hospice Plus',361,'Hospice Plus - Clear Lake (Egret Bay), TX','Location'),
			(569,'SS) Curo : Hospice Plus - Weatherford, TX',3445,'Hospice Plus - Weatherford, TX',209,'Hospice Plus',366,'Hospice Plus - Weatherford, TX','Location'),
			(572,'SS) Curo : Hospice Plus - Arlington, TX',3421,'Hospice Plus - Arlington, TX',209,'Hospice Plus',349,'Hospice Plus - Arlington, TX','Location'),
			(573,'SS) Curo : New Century - Pleasanton, TX',3464,'New Century - Pleasanton, TX',209,'Hospice Plus',375,'New Century - Pleasanton, TX','Location'),
			(575,'SS) Curo : Hospice Plus - Cypress (Jones Rd), TX',3428,'Hospice Plus - Cypress (Jones Rd), TX',209,'Hospice Plus',360,'Hospice Plus - Cypress (Jones Rd), TX','Location'),
			(576,'SS) Curo : Hospice Plus - Kingwood, TX',3432,'Hospice Plus - Kingwood, TX',209,'Hospice Plus',357,'Hospice Plus - Kingwood, TX','Location'),
			(577,'SS) Curo : Hospice Plus - Mt Pleasant, TX',3436,'Hospice Plus - Mt Pleasant, TX',209,'Hospice Plus',353,'Hospice Plus - Mt Pleasant, TX','Location'),
			(580,'SS) Curo : Hospice Plus - Beaumont, TX',3423,'Hospice Plus - Beaumont, TX',209,'Hospice Plus',363,'Hospice Plus - Beaumont, TX','Location'),
			(583,'SS) Curo : New Century - Marble Falls, TX',3462,'New Century - Marble Falls, TX',209,'Hospice Plus',374,'New Century - Marble Falls, TX','Location'),
			(584,'Affinity - Lufkin, TX',2048,'Affinity - Lufkin, TX',16,'Affinity Hospice, LLC',23,'Affinity - Lufkin, TX','Location'),
			(587,'SS) Altus - Beaumont, TX',2058,'Altus - Beaumont, TX',23,'Altus Hospice Management, LP',34,'Altus - Beaumont, TX','Location'),
			(588,'SS) Altus - Houston (North), TX',2060,'Altus - Houston (North), TX',23,'Altus Hospice Management, LP',35,'Altus - Houston (North), TX','Location'),
			(594,'Charter (CA) - Covina, CA',2121,'Charter (CA) - Covina, CA',61,'Charter Hospice, Inc (CA)',94,'Charter (CA) - Covina, CA','Location'),
			(601,'Eden - Diamond Bar, CA',2169,'Eden - Diamond Bar, CA',82,'Eden Hospice Care, Inc',135,'Eden - Diamond Bar, CA','Location'),
			(607,'SS) Curo : New Century - Austin, TX',3449,'New Century - Austin, TX',210,'New Century Hospice, Inc',367,'New Century - Austin, TX','Location'),
			(610,'Faith in Angels - Burbank, CA',2179,'Faith in Angels - Burbank, CA',86,'Faith in Angels Hospice (dba)',140,'Faith in Angels - Burbank, CA','Location'),
			(671,'Community (TX) - Ft Worth, TX',2131,'Community (TX) - Ft Worth, TX',68,'Community Hospice of Texas',105,'Community (TX) - Ft Worth, TX','Location'),
			(681,'Community (TX) - Cleburne, TX',2129,'Community (TX) - Cleburne, TX',68,'Community Hospice of Texas',103,'Community (TX) - Cleburne, TX','Location'),
			(691,'Community (TX) - Dallas, TX',2130,'Community (TX) - Dallas, TX',68,'Community Hospice of Texas',104,'Community (TX) - Dallas, TX','Location'),
			(701,'Community (TX-IPU) - Fort Worth, TX',2133,'Community (TX-IPU) - Fort Worth, TX',68,'Community Hospice of Texas',107,'Community (TX-IPU) - Fort Worth, TX','Location'),
			(711,'Community (TX-IPU) - Burleson, TX',2132,'Community (TX-IPU) - Burleson, TX',68,'Community Hospice of Texas',106,'Community (TX-IPU) - Burleson, TX','Location'),
			(721,'Community (TX-IPU) - Waco, TX',2348,'Community (TX-IPU) - Waco, TX',68,'Community Hospice of Texas',108,'Community (TX-IPU) - Waco, TX','Location'),
			(731,'Community (TX) - Whitney, TX',2351,'Community (TX) - Whitney, TX',68,'Community Hospice of Texas',111,'Community (TX) - Whitney, TX','Location'),
			(741,'Community (TX) - Mexia, TX',2349,'Community (TX) - Mexia, TX',68,'Community Hospice of Texas',109,'Community (TX) - Mexia, TX','Location'),
			(751,'Community (TX) - Waco, TX',2350,'Community (TX) - Waco, TX',68,'Community Hospice of Texas',110,'Community (TX) - Waco, TX','Location'),
			(801,'SS) CIMA (Rose of TX) - Woodlands, TX',null,null,null,null,null,null,null),
			(811,'SS) CIMA - Corpus Christi, TX',16238,'CIMA - Corpus Christi, TX',218,'CIMA Hospice',420,'CIMA - Corpus Christi, TX','Location'),
			(831,'Anchor - Houston, TX',2083,'Anchor - Houston, TX',33,'Anchor Hospice (dba)',47,'Anchor - Houston, TX','Location'),
			(841,'Absolute - Sacramento, CA',2625,'Absolute - Sacramento, CA',13,'Absolute Compassion, LLC',14,'Absolute - Sacramento, CA','Location'),
			(851,'Ace HHC&H - Orinda, CA',2730,'Ace HHC&H - Orinda, CA',113,'Ace Home Health Care & Hospice, Inc',182,'Ace HHC&H - Orinda, CA','Location'),
			(861,'American CareQuest - San Francisco, CA',40698,'American CareQuest - San Francisco, CA',30,'American CareQuest Hospice, Inc',613,'American CareQuest - San Francisco, CA','Location'),
			(881,'Asian Network - Oakland, CA',2630,'Asian Network - Oakland, CA',42,'Asian Network Hospice, Inc',68,'Asian Network - Oakland, CA','Location'),
			(951,'Collabria - Napa, CA',2638,'Collabria - Napa, CA',63,'Collabria Care',98,'Collabria - Napa, CA','Location'),
			(981,'Grace H&PC - San Ramon, CA',2193,'Grace H&PC - San Ramon, CA',95,'Grace Hospice & Palliative Care, Inc',151,'Grace H&PC - San Ramon, CA','Location'),
			(991,'SS) Heartland - Santa Clara, CA',42028,'Heartland - Santa Clara, CA',212,'HCR ManorCare, Inc',675,'Heartland - Santa Clara, CA','Location'),
			(1001,'SS) Heartland - Monterey, CA',40488,'Heartland - Monterey, CA',212,'HCR ManorCare, Inc',604,'Heartland - Monterey, CA','Location'),
			(1011,'SS) Heartland - San Rafael, CA',40489,'Heartland - San Rafael, CA',212,'HCR ManorCare, Inc',605,'Heartland - San Rafael, CA','Location'),
			(1021,'SS) Heartland - Santa Rosa, CA',40699,'Heartland - Santa Rosa, CA',212,'HCR ManorCare, Inc',614,'Heartland - Santa Rosa, CA','Location'),
			(1031,'Hinds - Fresno, CA',2243,'Hinds - Fresno, CA',105,'Hinds Hospice',170,'Hinds - Fresno, CA','Location'),
			(1041,'Hinds (IPU) - Fresno, CA',2242,'Hinds (IPU) - Fresno, CA',105,'Hinds Hospice',169,'Hinds (IPU) - Fresno, CA','Location'),
			(1051,'Hinds - Merced, CA',2244,'Hinds - Merced, CA',105,'Hinds Hospice',171,'Hinds - Merced, CA','Location'),
			(1061,'Hope (CA) - Dublin, CA',2261,'Hope (CA) - Dublin, CA',111,'Hope Hospice, Inc (CA)',180,'Hope (CA) - Dublin, CA','Location'),
			(1111,'East Bay (IPU-Bruns) - Alamo, CA',2167,'East Bay (IPU-Bruns) - Alamo, CA',119,'Hospice of the East Bay (dba)',190,'East Bay (IPU-Bruns) - Alamo, CA','Location'),
			(1121,'East Bay - Pleasant Hill, CA',2168,'East Bay - Pleasant Hill, CA',119,'Hospice of the East Bay (dba)',191,'East Bay - Pleasant Hill, CA','Location'),
			(1181,'LifeGuard - Pleasanton, CA',2299,'LifeGuard - Pleasanton, CA',135,'LifeGuard Hospice Care, Inc',210,'LifeGuard - Pleasanton, CA','Location'),
			(1221,'RX Staffing - Sacramento, CA',2362,'RX Staffing - Sacramento, CA',180,'RX Staffing Hospice Care (dba)',274,'RX Staffing - Sacramento, CA','Location'),
			(1251,'SS) Kindred - Dublin, CA',3064,'Kindred - Dublin, CA',219,'Kindred Healthcare, Inc',443,'Kindred - Dublin, CA','Location'),
			(1261,'SS) Kindred - San Jose, CA',3072,'Kindred - San Jose, CA',219,'Kindred Healthcare, Inc',439,'Kindred - San Jose, CA','Location'),
			(1381,'Private Pay (CA)',null,null,null,null,null,null,null),
			(1451,'SS) Holy Savior - San Antonio, TX',2250,'Holy Savior - San Antonio, TX',109,'Holy Savior Hospice (dba)',177,'Holy Savior - San Antonio, TX','Location'),
			(1481,'Harbor - Beaumont, TX',3048,'Harbor - Beaumont, TX',101,'Harbor Hospice of Texas',158,'Harbor - Beaumont, TX','Location'),
			(1491,'SS) Curo : New Century - San Antonio, TX',3466,'New Century - San Antonio, TX',210,'New Century Hospice, Inc',376,'New Century - San Antonio, TX','Location'),
			(1511,'SS) Altus - Austin, TX',2057,'Altus - Austin, TX',23,'Altus Hospice Management, LP',33,'Altus - Austin, TX','Location'),
			(1551,'Traditions - Conroe, TX',3083,'D) Traditions - Conroe, TX',75,'D) Traditions Hospice (dba)',126,'D) Traditions - Conroe, TX','Location'),
			(1611,'Fairmont - Richmond, TX',2177,'Fairmont - Richmond, TX',84,'Fairmont Hospice, LLC',137,'Fairmont - Richmond, TX','Location'),
			(1711,'St Joseph - Conroe, TX',2389,'St Joseph - Conroe, TX',192,'St Joseph Hospice (Carpenter Network)',288,'St Joseph - Conroe, TX','Location'),
			(1721,'Transcend - San Antonio (North), TX',2409,'Transcend - San Antonio (North), TX',248,'Transitions Hospice, LLC (TX)',511,'Transcend - San Antonio (North), TX','Location'),
			(1771,'Harbor - Corpus Christi, TX',3050,'Harbor - Corpus Christi, TX',101,'Harbor Hospice of Texas',159,'Harbor - Corpus Christi, TX','Location'),
			(1811,'American Medical - Corpus Christi, TX',2080,'American Medical - Corpus Christi, TX',31,'American Medical Hospice Care, LLC',45,'American Medical - Corpus Christi, TX','Location'),
			(1821,'SS) Curo : New Century - Dallas, TX',3455,'New Century - Dallas, TX',210,'New Century Hospice, Inc',370,'New Century - Dallas, TX','Location'),
			(1831,'A-1 - Burbank, CA',2033,'A-1 - Burbank, CA',10,'A-1 Hospice Care, Inc',10,'A-1 - Burbank, CA','Location'),
			(1841,'Angels Smile - Los Angeles, CA',2085,'Angels Smile - Los Angeles, CA',35,'Angels Smile Hospice, Inc',49,'Angels Smile - Los Angeles, CA','Location'),
			(1851,'Care First HS - San Dimas, CA',16351,'Care First HS - San Dimas, CA',56,'Care First Hospice Services, Inc',89,'Care First HS - San Dimas, CA','Location'),
			(2401,'SS) Curo : New Century - Fort Worth, TX',3457,'New Century - Fort Worth, TX',210,'New Century Hospice, Inc',372,'New Century - Fort Worth, TX','Location'),
			(2411,'SS) Curo : New Century - South TX (Victoria), TX (ADS)',3469,'New Century - South TX (Victoria), TX (ADS)',210,'New Century Hospice, Inc',378,'New Century - South TX (Victoria), TX (ADS)','Location'),
			(2421,'Transcend - Corpus Christi (North), TX',2407,'Transcend - Corpus Christi (North), TX',248,'Transitions Hospice, LLC (TX)',509,'Transcend - Corpus Christi (North), TX','Location'),
			(2471,'Freedom - N Richland Hills, TX',2181,'Freedom - N Richland Hills, TX',89,'Freedom Hospice, LLC',143,'Freedom - N Richland Hills, TX','Location'),
			(2481,'Americare - Burbank, CA',2081,'Americare - Burbank, CA',32,'Americare Hospice, Inc',46,'Americare - Burbank, CA','Location'),
			(2491,'Comfort Choice - Los Angeles, CA',2127,'Comfort Choice - Los Angeles, CA',66,'Comfort Choice Hospice',101,'Comfort Choice - Los Angeles, CA','Location'),
			(2501,'Continuum - Petaluma, CA',2149,'Continuum - Petaluma, CA',72,'Continuum Care Hospice, LLC',121,'Continuum - Petaluma, CA','Location'),
			(2521,'SS) Curo : New Century - Central TX (Harker Heights), TX',3453,'New Century - Central TX (Harker Heights), TX',210,'New Century Hospice, Inc',369,'New Century - Central TX (Harker Heights), TX','Location'),
			(2541,'SS) Curo : New Century - South TX (Corpus Christi), TX',3468,'New Century - South TX (Corpus Christi), TX',210,'New Century Hospice, Inc',377,'New Century - South TX (Corpus Christi), TX','Location'),
			(2581,'Chambers - Mt Pleasant, TX',2123,'Chambers - Mt Pleasant, TX',59,'Chambers Hospice (dba)',92,'Chambers - Mt Pleasant, TX','Location'),
			(2621,'St Arsenius HC - Pasadena, CA',2388,'St Arsenius HC - Pasadena, CA',191,'St Arsenius Hospice Care, Inc',287,'St Arsenius HC - Pasadena, CA','Location'),
			(2681,'Five Star - Pasadena, CA',2180,'Five Star - Pasadena, CA',88,'Five Star Home Hospice, Inc',142,'Five Star - Pasadena, CA','Location'),
			(2701,'SS) Holy Savior - Dallas, TX',2249,'Holy Savior - Dallas, TX',109,'Holy Savior Hospice (dba)',175,'Holy Savior - Dallas, TX','Location'),
			(2761,'Affinity - Jasper, TX',2047,'Affinity - Jasper, TX',16,'Affinity Hospice, LLC',22,'Affinity - Jasper, TX','Location'),
			(2771,'Affinity - Center, TX',2046,'Affinity - Center, TX',16,'Affinity Hospice, LLC',21,'Affinity - Center, TX','Location'),
			(2791,'Charity HC - Carson, CA',2120,'Charity HC - Carson, CA',60,'Charity Hospice Care, Inc',93,'Charity HC - Carson, CA','Location'),
			(2881,'SS) Curo : New Century - Kerrville, TX',3460,'New Century - Kerrville, TX',210,'New Century Hospice, Inc',373,'New Century - Kerrville, TX','Location'),
			(3011,'SS) Curo : New Century - Denton, TX (ADS)',3456,'New Century - Denton, TX (ADS)',210,'New Century Hospice, Inc',371,'New Century - Denton, TX (ADS)','Location'),
			(3181,'Heritage (E TX) - Tyler, TX',null,null,null,null,null,null,null),
			(3191,'Torrance Memorial - Torrance, CA',2403,'Torrance Memorial - Torrance, CA',244,'Torrance Memorial Hospice (dba)',505,'Torrance Memorial - Torrance, CA','Location'),
			(3221,'SS) Kindred - Pleasant Hill, CA',3070,'Kindred - Pleasant Hill, CA',219,'Kindred Healthcare, Inc',440,'Kindred - Pleasant Hill, CA','Location'),
			(3311,'SS) Curo : Hospice Plus - Sugar Land, TX',3440,'Hospice Plus - Sugar Land, TX',209,'Hospice Plus',351,'Hospice Plus - Sugar Land, TX','Location'),
			(3381,'A-Med - Nederland, TX',2036,'A-Med - Nederland, TX',11,'A-Med Health, Inc',11,'A-Med - Nederland, TX','Location'),
			(3401,'SS) Curo : Hospice Plus - Lufkin, TX',3435,'Hospice Plus - Lufkin, TX',209,'Hospice Plus',354,'Hospice Plus - Lufkin, TX','Location'),
			(3411,'SS) Curo : New Century - Beeville, TX',3451,'New Century - Beeville, TX',210,'New Century Hospice, Inc',368,'New Century - Beeville, TX','Location'),
			(3431,'Hollywood - Toluca Lake, CA',2247,'Hollywood - Toluca Lake, CA',107,'Hollywood Hospice (dba)',173,'Hollywood - Toluca Lake, CA','Location'),
			(3561,'Tapestry - Calhoun, GA',2396,'Tapestry - Calhoun, GA',239,'Tapestry Hospice of Northwest Georgia',487,'Tapestry - Calhoun, GA','Location'),
			(3571,'Halcyon - Austin, TX',2198,'Halcyon - Austin, TX',98,'Halcyon Home, LLC',154,'Halcyon - Austin, TX','Location'),
			(3591,'SS) UTMC - Knoxville, TN',2867,'UTMC - Knoxville, TN',224,'UTMC Home Care & Hospice Services (dba)',456,'UTMC - Knoxville, TN','Location'),
			(3631,'SS) Amedisys - Athens, TN',2067,'Amedisys - Athens, TN',200,'Amedisys, Inc',305,'Amedisys - Athens, TN','Location'),
			(3641,'SS) Amedisys - Chattanooga, TN',2068,'Amedisys - Chattanooga, TN',200,'Amedisys, Inc',322,'Amedisys - Chattanooga, TN','Location'),
			(3651,'SS) Amedisys - Dalton, GA',2069,'Amedisys - Dalton, GA',200,'Amedisys, Inc',321,'Amedisys - Dalton, GA','Location'),
			(3681,'SS) Amedisys - Kimball, TN',2072,'Amedisys - Kimball, TN',200,'Amedisys, Inc',320,'Amedisys - Kimball, TN','Location'),
			(3721,'SS) Amedisys - Knoxville, TN',2073,'Amedisys - Knoxville, TN',200,'Amedisys, Inc',319,'Amedisys - Knoxville, TN','Location'),
			(3731,'SS) Kindred - Cleveland, TN',3061,'Kindred - Cleveland, TN',219,'Kindred Healthcare, Inc',445,'Kindred - Cleveland, TN','Location'),
			(3761,'SS) Curo : Avalon - Chattanooga (RCC), TN',3308,'Avalon - Chattanooga (RCC), TN',207,'Avalon Hospice',336,'Avalon - Chattanooga (RCC), TN','Location'),
			(3781,'SS) Curo : Avalon - Crossville, TN',3409,'Avalon - Crossville, TN',207,'Avalon Hospice',338,'Avalon - Crossville, TN','Location'),
			(3811,'SS) Curo : Avalon - Morristown, TN',3415,'Avalon - Morristown, TN',207,'Avalon Hospice',340,'Avalon - Morristown, TN','Location'),
			(3821,'SS) Curo : Avalon - Sweetwater, TN',3418,'Avalon - Sweetwater, TN',207,'Avalon Hospice',341,'Avalon - Sweetwater, TN','Location'),
			(3831,'SS) Curo : Avalon - Tullahoma, TN',3419,'Avalon - Tullahoma, TN',207,'Avalon Hospice',342,'Avalon - Tullahoma, TN','Location'),
			(3841,'SS) Compassus - Houston (East), TX',2140,'Compassus - Houston (East), TX',216,'Hospice Compassus, Inc',403,'Compassus - Houston (East), TX','Location'),
			(3851,'SS) Compassus - Houston (West), TX',2141,'Compassus - Houston (West), TX',216,'Hospice Compassus, Inc',404,'Compassus - Houston (West), TX','Location'),
			(3881,'SS) VITAS - Houston (Central), TX',3092,'VITAS - Houston (Central), TX',236,'VITAS HCC - Texas',483,'VITAS - Houston (Central), TX','Location'),
			(3891,'SS) VITAS (IPU) - Houston, TX',3089,'VITAS (IPU) - Houston, TX',236,'VITAS HCC - Texas',482,'VITAS (IPU) - Houston, TX','Location'),
			(3921,'SS) CIMA (Grapevine Mission) - Grand Prairie, TX',15624,'CIMA (Grapevine Mission) - Grand Prairie, TX',218,'CIMA Hospice',418,'CIMA (Grapevine Mission) - Grand Prairie, TX','Location'),
			(3941,'SS) Amedisys - Sweetwater, TN',2077,'Amedisys - Sweetwater, TN',200,'Amedisys, Inc',317,'Amedisys - Sweetwater, TN','Location'),
			(3951,'Oyuna - Fresno, CA',2330,'Oyuna - Fresno, CA',158,'Oyuna Hospice, Inc',233,'Oyuna - Fresno, CA','Location'),
			(3991,'Kindle - Houston, TX',32108,'Kindle - Houston, TX',130,'Kindle Hospice and Palliative Care dba Kindle Hospice, LLC',205,'Kindle - Houston, TX','Location'),
			(4111,'Elara Caring (Mission) - Cleburne, TX',null,null,null,null,null,null,null),
			(4261,'Assured - Cartersville, GA',2091,'Assured - Cartersville, GA',44,'Assured Hospice Care, LLC',70,'Assured - Cartersville, GA','Location'),
			(4311,'Transitions (GA) - Rome, GA',2406,'Transitions (GA) - Rome, GA',247,'Transitions Hospice Care of Georgia, Inc',508,'Transitions (GA) - Rome, GA','Location'),
			(4321,'Infinite - Encino, CA',2277,'Infinite - Encino, CA',122,'Infinite Hospice Care, Inc',197,'Infinite - Encino, CA','Location'),
			(4331,'SS) Kindred (Gentiva) - Athens, GA',3057,'Kindred - Athens, GA',219,'Kindred Healthcare, Inc',426,'Kindred - Athens, GA','Location'),
			(4341,'SS) Kindred (Gentiva) - Atlanta (Odyssey/East), GA',3059,'Kindred - Atlanta (Odyssey/East), GA',219,'Kindred Healthcare, Inc',446,'Kindred - Atlanta (Odyssey/East), GA','Location'),
			(4351,'SS) Kindred (Gentiva) - Atlanta (North/West), GA',3058,'Kindred - Atlanta (North/West), GA',219,'Kindred Healthcare, Inc',447,'Kindred - Atlanta (North/West), GA','Location'),
			(4361,'SS) Bristol - Atlanta, GA',2104,'Bristol - Atlanta, GA',203,'Bristol Hospice, LLC',327,'Bristol - Atlanta, GA','Location'),
			(4421,'SS) Kindred (Gentiva) - Douglasville, GA',3063,'Kindred - Douglasville, GA',219,'Kindred Healthcare, Inc',444,'Kindred - Douglasville, GA','Location'),
			(4431,'SS) Kindred (Gentiva) - Gainesville, GA',3067,'Kindred - Gainesville, GA',219,'Kindred Healthcare, Inc',442,'Kindred - Gainesville, GA','Location'),
			(4441,'SS) Kindred (Gentiva) - Newnan, GA',3069,'Kindred - Newnan, GA',219,'Kindred Healthcare, Inc',441,'Kindred - Newnan, GA','Location'),
			(4451,'SS) Kindred (Gentiva) - Stockbridge, GA',3073,'Kindred - Stockbridge, GA',219,'Kindred Healthcare, Inc',438,'Kindred - Stockbridge, GA','Location'),
			(4461,'SS) Kindred (Gentiva) - Warner Robins (Macon), GA',3074,'Kindred - Warner Robins (Macon), GA',219,'Kindred Healthcare, Inc',437,'Kindred - Warner Robins (Macon), GA','Location'),
			(4471,'SS) Heartland - Cartersville, GA',2232,'Heartland - Cartersville, GA',212,'HCR ManorCare, Inc',387,'Heartland - Cartersville, GA','Location'),
			(4481,'SS) Compassus - Calhoun, GA',2770,'Compassus - Calhoun, GA',216,'Hospice Compassus, Inc',408,'Compassus - Calhoun, GA','Location'),
			(4491,'SS) Compassus - Fayetteville, GA',2772,'Compassus - Fayetteville, GA',216,'Hospice Compassus, Inc',410,'Compassus - Fayetteville, GA','Location'),
			(4501,'SS) Compassus - Tucker, GA',2775,'Compassus - Tucker, GA',216,'Hospice Compassus, Inc',412,'Compassus - Tucker, GA','Location'),
			(4521,'SS) Curo : Regency-SouthernCare - Kennesaw, GA',3481,'Regency-SouthernCare - Kennesaw, GA',211,'Regency Hospice',384,'Regency-SouthernCare - Kennesaw, GA','Location'),
			(4531,'SS) Curo : Regency-SouthernCare - Hiawassee, GA',3480,'Regency-SouthernCare - Hiawassee, GA',211,'Regency Hospice',383,'Regency-SouthernCare - Hiawassee, GA','Location'),
			(4541,'SS) Curo : Regency-SouthernCare - Athens, GA',3474,'Regency-SouthernCare - Athens, GA',211,'Regency Hospice',379,'Regency-SouthernCare - Athens, GA','Location'),
			(4551,'North Georgia Community - Dalton, GA',3152,'North Georgia Community - Dalton, GA',151,'North Georgia Community Hospice, LLC',226,'North Georgia Community - Dalton, GA','Location'),
			(4591,'Q) Georgia Mountains - Jasper, GA',2186,'Georgia Mountains - Jasper, GA',170,'Georgia Mountains Hospice, Inc',249,'Georgia Mountains - Jasper, GA','Location'),
			(4601,'SS) Encompass - Macon, GA',2781,'Encompass - Macon, GA',213,'Encompass Home Health, Inc',687,'Encompass - Macon, GA','Location'),
			(4611,'SS) Homestead - Athens, GA',2253,'Homestead - Athens, GA',215,'Homestead Hospice Management, LLC',392,'Homestead - Athens, GA','Location'),
			(4621,'SS) Homestead - Blairsville, GA',2254,'Homestead - Blairsville, GA',215,'Homestead Hospice Management, LLC',393,'Homestead - Blairsville, GA','Location'),
			(4631,'SS) Homestead - Cartersville, GA',2255,'Homestead - Cartersville, GA',215,'Homestead Hospice Management, LLC',394,'Homestead - Cartersville, GA','Location'),
			(4641,'SS) Homestead - Dalton, GA',2256,'Homestead - Dalton, GA',215,'Homestead Hospice Management, LLC',395,'Homestead - Dalton, GA','Location'),
			(4651,'SS) Homestead - Roswell, GA',2259,'Homestead - Roswell, GA',215,'Homestead Hospice Management, LLC',398,'Homestead - Roswell, GA','Location'),
			(4671,'SS) Pine Pointe - Macon, GA',2342,'Pine Pointe - Macon, GA',226,'Pine Pointe Hospice & Palliative Care (dba)',459,'Pine Pointe - Macon, GA','Location'),
			(4701,'SS) Weinstein - Atlanta, GA',2425,'Weinstein - Atlanta, GA',232,'The Vi & Milton Weinstein Hospice, Inc',477,'Weinstein - Atlanta, GA','Location'),
			(4711,'SS) VITAS - Atlanta (North), GA',3090,'VITAS - Atlanta (North), GA',235,'VITAS HCC - Georgia',480,'VITAS - Atlanta (North), GA','Location'),
			(4721,'SS) VITAS - Atlanta (South), GA',3091,'VITAS - Atlanta (South), GA',235,'VITAS HCC - Georgia',481,'VITAS - Atlanta (South), GA','Location'),
			(4751,'SS) Curo : Avalon - Knoxville, TN',3413,'Avalon - Knoxville, TN',207,'Avalon Hospice',339,'Avalon - Knoxville, TN','Location'),
			(4761,'SS) Amedisys - Lawrenceville, GA',2074,'Amedisys - Lawrenceville, GA',200,'Amedisys, Inc',318,'Amedisys - Lawrenceville, GA','Location'),
			(4781,'SS) Applied P&HS - Rancho Cordova, CA',2086,'Applied P&HS - Rancho Cordova, CA',36,'Applied Palliative & Hospice Services, Inc',50,'Applied P&HS - Rancho Cordova, CA','Location'),
			(4791,'SS) Compassus - Ellijay, GA',2771,'Compassus - Ellijay, GA',216,'Hospice Compassus, Inc',409,'Compassus - Ellijay, GA','Location'),
			(4801,'SS) Encompass - Lawrenceville, GA',null,null,null,null,null,null,null),
			(4831,'SS) Curo : Regency-SouthernCare - Macon, GA',3482,'Regency-SouthernCare - Macon, GA',211,'Regency Hospice',385,'Regency-SouthernCare - Macon, GA','Location'),
			(4881,'SS) Pine Pointe (IPU) - Macon, GA',2341,'Pine Pointe (IPU) - Macon, GA',226,'Pine Pointe Hospice & Palliative Care (dba)',458,'Pine Pointe (IPU) - Macon, GA','Location'),
			(4931,'SS) Bristol - Waxahachie, TX',2106,'Bristol - Waxahachie, TX',203,'Bristol Hospice, LLC',329,'Bristol - Waxahachie, TX','Location'),
			(4951,'SS) Encompass - Marietta, GA',null,null,null,null,null,null,null),
			(4961,'SS) Homestead - Newnan, GA',2258,'Homestead - Newnan, GA',215,'Homestead Hospice Management, LLC',397,'Homestead - Newnan, GA','Location'),
			(4971,'SS) Homestead - Jackson, GA',2257,'Homestead - Jackson, GA',215,'Homestead Hospice Management, LLC',396,'Homestead - Jackson, GA','Location'),
			(4981,'SS) Homestead - Warner Robins, GA',2260,'Homestead - Warner Robins, GA',215,'Homestead Hospice Management, LLC',399,'Homestead - Warner Robins, GA','Location'),
			(4991,'SS) Serenity (GA) - Warner Robins, GA',2375,'Serenity (GA) - Warner Robins, GA',229,'Serenity Hospice Care, LLC',468,'Serenity (GA) - Warner Robins, GA','Location'),
			(5002,'SS) Curo : Regency-SouthernCare - Vidalia, GA',3484,'Regency-SouthernCare - Vidalia, GA',211,'Regency Hospice',386,'Regency-SouthernCare - Vidalia, GA','Location'),
			(5003,'SS) Curo : Regency-SouthernCare - Conyers, GA',3478,'Regency-SouthernCare - Conyers, GA',211,'Regency Hospice',381,'Regency-SouthernCare - Conyers, GA','Location'),
			(5006,'Avatar HHC - Spring, TX',2094,'Avatar HHC - Spring, TX',47,'Avatar & Millennium Agencies',74,'Avatar HHC - Spring, TX','Location'),
			(5009,'SS) Curo : Regency-SouthernCare - Dalton, GA',3479,'Regency-SouthernCare - Dalton, GA',211,'Regency Hospice',382,'Regency-SouthernCare - Dalton, GA','Location'),
			(5012,'SS) Amedisys - Newnan, GA',3765,'Amedisys - Newnan, GA',200,'Amedisys, Inc',315,'Amedisys - Newnan, GA','Location'),
			(5013,'SS) Amedisys - Toccoa, GA',2078,'Amedisys - Toccoa, GA',200,'Amedisys, Inc',316,'Amedisys - Toccoa, GA','Location'),
			(5018,'Lynncare - Weslaco, TX',2303,'Lynncare - Weslaco, TX',250,'United HCS & Lynncare HS',516,'Lynncare - Weslaco, TX','Location'),
			(5020,'SS) Curo : Regency-SouthernCare - College Park, GA',3477,'Regency-SouthernCare - College Park, GA',211,'Regency Hospice',380,'Regency-SouthernCare - College Park, GA','Location'),
			(5023,'SS) Halcyon - Atlanta, GA',2786,'Halcyon - Atlanta, GA',221,'Halcyon Hospice',451,'Halcyon - Atlanta, GA','Location'),
			(5026,'SS) Halcyon - Gainesville, GA',2789,'Halcyon - Gainesville, GA',221,'Halcyon Hospice',453,'Halcyon - Gainesville, GA','Location'),
			(5028,'SS) Heartlite - Dalton, GA',2791,'Heartlite - Dalton, GA',222,'Heartlite Hospice (dba)',454,'Heartlite - Dalton, GA','Location'),
			(5029,'Traditions - Houston (North), TX',3084,'D) Traditions - Houston (North), TX',75,'D) Traditions Hospice (dba)',127,'D) Traditions - Houston (North), TX','Location'),
			(5030,'VNA of TX - Dallas,TX',2420,'VNA of TX - Dallas, TX',255,'Visiting Nurse Association of Texas (The)',522,'VNA of TX - Dallas, TX','Location'),
			(5031,'VNA of TX - Denton, TX',2421,'VNA of TX - Denton, TX',255,'Visiting Nurse Association of Texas (The)',523,'VNA of TX - Denton, TX','Location'),
			(5032,'VNA of TX - Kaufman, TX',2422,'VNA of TX - Kaufman, TX',255,'Visiting Nurse Association of Texas (The)',524,'VNA of TX - Kaufman, TX','Location'),
			(5033,'VNA of TX - McKinney, TX',2423,'VNA of TX - McKinney, TX',255,'Visiting Nurse Association of Texas (The)',525,'VNA of TX - McKinney, TX','Location'),
			(5035,'SS) Halcyon - Cumming, GA',2788,'Halcyon - Cumming, GA',221,'Halcyon Hospice',452,'Halcyon - Cumming, GA','Location'),
			(5037,'SS) The Medical Team - San Antonio, TX',2400,'The Medical Team - San Antonio, TX',231,'The Medical Team, Inc',473,'The Medical Team - San Antonio, TX','Location'),
			(5041,'Progressive HH&HC - Modesto, CA',3075,'Progressive HH&HC - Modesto, CA',166,'Progressive Home Health & Hospice Care, LLC',244,'Progressive HH&HC - Modesto, CA','Location'),
			(5044,'SS) VITAS (SPA) - Ft Worth, TX',null,null,null,null,null,null,null),
			(5046,'Seasons of Life - Lake Forest, CA',2370,'Seasons of Life - Lake Forest, CA',184,'Seasons of Life Hospice, LLC',280,'Seasons of Life - Lake Forest, CA','Location'),
			(5049,'SS) Encompass - Houston, TX',2779,'Encompass - Houston, TX',213,'Encompass Home Health, Inc',388,'Encompass - Houston, TX','Location'),
			(5058,'SS) Curo : Avalon - Winchester, TN',3420,'Avalon - Winchester, TN',207,'Avalon Hospice',343,'Avalon - Winchester, TN','Location'),
			(5065,'Q) Capstone - Norcross, GA',2112,'Capstone - Norcross, GA',168,'Capstone Hospice, LLC',246,'Capstone - Norcross, GA','Location'),
			(5068,'SS) Brookdale - Arlington (DFW), TX',2107,'Brookdale - Arlington (DFW), TX',204,'Brookdale Senior Living, Inc',330,'Brookdale - Arlington (DFW), TX','Location'),
			(5078,'SS) Brookdale - Houston, TX',2108,'Brookdale - Houston, TX',204,'Brookdale Senior Living, Inc',331,'Brookdale - Houston, TX','Location'),
			(5079,'SS) Compassus - Dallas, TX',2138,'Compassus - Dallas, TX',216,'Hospice Compassus, Inc',401,'Compassus - Dallas, TX','Location'),
			(5080,'SS) Compassus - Ft Worth, TX',2139,'Compassus - Ft Worth, TX',216,'Hospice Compassus, Inc',402,'Compassus - Ft Worth, TX','Location'),
			(5081,'SS) Compassus - McKinney, TX',2143,'Compassus - McKinney, TX',216,'Hospice Compassus, Inc',406,'Compassus - McKinney, TX','Location'),
			(5082,'SS) Bristol - The Woodlands, TX',2105,'Bristol - The Woodlands, TX',203,'Bristol Hospice, LLC',328,'Bristol - The Woodlands, TX','Location'),
			(5086,'SS) The Medical Team - Brownsville, TX',3274,'The Medical Team - Brownsville, TX',231,'The Medical Team, Inc',474,'The Medical Team - Brownsville, TX','Location'),
			(5088,'SS) The Medical Team - Austin, TX',3281,'The Medical Team - Austin, TX',231,'The Medical Team, Inc',475,'The Medical Team - Austin, TX','Location'),
			(5090,'SS) Curo : Avalon - Chattanooga (East-RCH), TN',3309,'Avalon - Chattanooga (East-RCH), TN',207,'Avalon Hospice',337,'Avalon - Chattanooga (East-RCH), TN','Location'),
			(5096,'Amavi - Brentwood, CA',3626,'Amavi - Brentwood, CA',26,'Amavi Home Health & Hospice Care Services, Inc',40,'Amavi - Brentwood, CA','Location'),
			(5097,'Blossom Ridge - Sacramento, CA',3628,'Blossom Ridge - Sacramento, CA',53,'Blossom Ridge Home Health Agency, LLC',83,'Blossom Ridge - Sacramento, CA','Location'),
			(5099,'Companion - Culver City, CA',3659,'Companion - Culver City, CA',69,'Companion Home Health & Hospice Corp',112,'Companion - Culver City, CA','Location'),
			(5100,'Companion - Downey, CA',3660,'Companion - Downey, CA',69,'Companion Home Health & Hospice Corp',113,'Companion - Downey, CA','Location'),
			(5101,'Companion - Orange, CA',3661,'Companion - Orange, CA',69,'Companion Home Health & Hospice Corp',114,'Companion - Orange, CA','Location'),
			(5102,'Companion - Pasadena, CA',3662,'Companion - Pasadena, CA',69,'Companion Home Health & Hospice Corp',115,'Companion - Pasadena, CA','Location'),
			(5103,'Companion - Riverside, CA',3663,'Companion - Riverside, CA',69,'Companion Home Health & Hospice Corp',116,'Companion - Riverside, CA','Location'),
			(5104,'Companion - Simi Valley, CA',3664,'Companion - Simi Valley, CA',69,'Companion Home Health & Hospice Corp',117,'Companion - Simi Valley, CA','Location'),
			(5106,'SS) Kindred - Palm Desert, CA',3671,'Kindred - Palm Desert, CA',219,'Kindred Healthcare, Inc',436,'Kindred - Palm Desert, CA','Location'),
			(5107,'SS) Kindred - San Bernardino, CA',3674,'Kindred - San Bernardino, CA',219,'Kindred Healthcare, Inc',435,'Kindred - San Bernardino, CA','Location'),
			(5108,'SS) Kindred - Victorville, CA',3675,'Kindred - Victorville, CA',219,'Kindred Healthcare, Inc',434,'Kindred - Victorville, CA','Location'),
			(5110,'SS) Compassus - Athens, GA',3680,'Compassus - Athens, GA',216,'Hospice Compassus, Inc',413,'Compassus - Athens, GA','Location'),
			(5114,'SS) Encompass - The Woodlands, TX',null,null,null,null,null,null,null),
			(5115,'Harbor - Tyler, TX',3695,'Harbor - Tyler, TX',101,'Harbor Hospice of Texas',164,'Harbor - Tyler, TX','Location'),
			(5117,'Amara (IPU) - Edinburg, TX',3705,'Amara (IPU) - Edinburg, TX',25,'Amara Hospice (dba)',39,'Amara (IPU) - Edinburg, TX','Location'),
			(5120,'Capitol - Austin, TX',3714,'Capitol - Austin, TX',55,'Capitol Hospice (dba)',88,'Capitol - Austin, TX','Location'),
			(5122,'SS) Brookdale - San Jose, CA',3718,'Brookdale - San Jose, CA',204,'Brookdale Senior Living, Inc',332,'Brookdale - San Jose, CA','Location'),
			(5125,'SS) PruittHealth - Atlanta, GA',3738,'PruittHealth - Atlanta, GA',227,'PruittHealth Corporation',461,'PruittHealth - Atlanta, GA','Location'),
			(5126,'SS) PruittHealth - Athens, GA',3737,'PruittHealth - Athens, GA',227,'PruittHealth Corporation',460,'PruittHealth - Athens, GA','Location'),
			(5127,'SS) PruittHealth - Calhoun, GA',null,null,null,null,null,null,null),
			(5128,'SS) PruittHealth - Gainesville, GA',3741,'PruittHealth - Gainesville, GA',227,'PruittHealth Corporation',463,'PruittHealth - Gainesville, GA','Location'),
			(5129,'SS) PruittHealth - Rome, GA',3743,'PruittHealth - Rome, GA',227,'PruittHealth Corporation',465,'PruittHealth - Rome, GA','Location'),
			(5130,'SS) PruittHealth - Macon, GA',3742,'PruittHealth - Macon, GA',227,'PruittHealth Corporation',464,'PruittHealth - Macon, GA','Location'),
			(5131,'SS) PruittHealth - Blue Ridge, GA',3739,'PruittHealth - Blue Ridge, GA',227,'PruittHealth Corporation',462,'PruittHealth - Blue Ridge, GA','Location'),
			(5132,'SS) PruittHealth - Union City, GA',3744,'PruittHealth - Union City, GA',227,'PruittHealth Corporation',466,'PruittHealth - Union City, GA','Location'),
			(5134,'Professional (dba) - Beaumont, TX',3760,'Professional (dba) - Beaumont, TX',164,'Professional Health Care (dba)',242,'Professional (dba) - Beaumont, TX','Location'),
			(5136,'Longevity - Panorama City, CA',3762,'Longevity - Panorama City, CA',139,'Longevity Hospice, Inc',214,'Longevity - Panorama City, CA','Location'),
			(5138,'Assured (IPU) - Cartersville, GA',31447,'Assured (IPU) - Cartersville, GA',44,'Assured Hospice Care, LLC',71,'Assured (IPU) - Cartersville, GA','Location'),
			(5144,'Life Springs - Fremont, CA',3793,'Life Springs - Fremont, CA',134,'Life Springs Hospice Care, Inc',209,'Life Springs - Fremont, CA','Location'),
			(5145,'Latreia - Rancho Cordova, CA',3795,'Latreia - Rancho Cordova, CA',132,'Latreia Healthcare Services, LLC',207,'Latreia - Rancho Cordova, CA','Location'),
			(5146,'AMA H&PC - Van Nuys, CA',3809,'AMA H&PC - Van Nuys, CA',24,'AMA Hospice & Palliative Care, Inc',37,'AMA H&PC - Van Nuys, CA','Location'),
			(5149,'St Marys HS - Fresno, CA',3872,'St Marys HS - Fresno, CA',195,'St Marys Hospice Services, Inc',291,'St Marys HS - Fresno, CA','Location'),
			(5151,'Arcturus - Peachtree Corners, GA',3875,'Arcturus - Peachtree Corners, GA',37,'Arcturus Healthcare, LLC',51,'Arcturus - Peachtree Corners, GA','Location'),
			(5158,'Arcturus - Peachtree Corners, GA',3875,'Arcturus - Peachtree Corners, GA',37,'Arcturus Healthcare, LLC',51,'Arcturus - Peachtree Corners, GA','Location'),
			(5161,'Our Caring Hands - Brownsville, TX',3979,'Our Caring Hands - Brownsville, TX',157,'Our Caring Hands Hospice & Palliative Care, LLC',232,'Our Caring Hands - Brownsville, TX','Location'),
			(5163,'SS) The Medical Team - Hebbronville, TX',3981,'The Medical Team - Hebbronville, TX',231,'The Medical Team, Inc',476,'The Medical Team - Hebbronville, TX','Location'),
			(5164,'SS) Advanced HH&H - Sacramento, CA',11186,'Advanced HH&H - Sacramento, CA',198,'Advanced Home Health & Hospice, Inc',300,'Advanced HH&H - Sacramento, CA','Location'),
			(5165,'Baylor Scott & White - Temple, TX',11183,'Baylor Scott & White - Temple, TX',48,'Baylor Scott & White Health',76,'Baylor Scott & White - Temple, TX','Location'),
			(5166,'Texas Elite - New Caney, TX',11181,'Texas Elite - New Caney, TX',241,'Texas Elite Hospice, LLC',492,'Texas Elite - New Caney, TX','Location'),
			(5167,'Serene Meadows - Arlington, TX',16463,'Serene Meadows - Arlington, TX',185,'Serene Meadows Hospice, LLC',281,'Serene Meadows - Arlington, TX','Location'),
			(5168,'Baylor Scott & White - Waco, TX',11184,'Baylor Scott & White - Waco, TX',48,'Baylor Scott & White Health',77,'Baylor Scott & White - Waco, TX','Location'),
			(5170,'Charter (CA) - Simi Valley, CA',14909,'Charter (CA) - Simi Valley, CA',61,'Charter Hospice, Inc (CA)',95,'Charter (CA) - Simi Valley, CA','Location'),
			(5171,'Saint Andrew - Garland, TX',30963,'Saint Andrew - Garland, TX',181,'Saint Andrew Hospice, LLC',275,'Saint Andrew - Garland, TX','Location'),
			(5173,'Infinity CS - Stockton, CA',16459,'Infinity CS - Stockton, CA',123,'Infinity Care Services, Inc',198,'Infinity CS - Stockton, CA','Location'),
			(5179,'Serenity HS - Houston, TX',10579,'Serenity HS - Houston, TX',186,'Serenity Hospice Solutions (dba)',282,'Serenity HS - Houston, TX','Location'),
			(5180,'Q) Caris - Athens, TN',null,null,null,null,null,null,null),
			(5183,'Cambridge - Stanton, CA',14910,'Cambridge - Stanton, CA',61,'Charter Hospice, Inc (CA)',96,'Cambridge - Stanton, CA','Location'),
			(5186,'SS) River City - Corpus Christi, TX',29940,'River City - Corpus Christi, TX',228,'River City Hospice, LLC',467,'River City - Corpus Christi, TX','Location'),
			(5190,'SS) Sutter Care - Sacramento, CA',30046,'Sutter Care - Sacramento, CA',230,'Sutter Care at Home (dba)',472,'Sutter Care - Sacramento, CA','Location'),
			(5191,'Hope - New Braunfels, TX',16357,'Hope - New Braunfels, TX',110,'Hope Hospice (TX)',178,'Hope - New Braunfels, TX','Location'),
			(5192,'SS) Sutter Care - Roseville, CA',29945,'Sutter Care - Roseville, CA',230,'Sutter Care at Home (dba)',471,'Sutter Care - Roseville, CA','Location'),
			(5193,'SS) Sutter Care - Concord, CA',29944,'Sutter Care - Concord, CA',230,'Sutter Care at Home (dba)',470,'Sutter Care - Concord, CA','Location'),
			(5194,'SS) Sutter Care - Alameda, CA',40595,'Sutter Care - Alameda, CA',230,'Sutter Care at Home (dba)',608,'Sutter Care - Alameda, CA','Location'),
			(5195,'SS) Sutter Care - Yuba City, CA',30048,'Sutter Care - Yuba City, CA',230,'Sutter Care at Home (dba)',615,'Sutter Care - Yuba City, CA','Location'),
			(5196,'SS) Christus - Corpus Christi',31290,'Christus - Corpus Christi, TX',220,'Christus Continuing Care',450,'Christus - Corpus Christi, TX','Location'),
			(5197,'Reliant HH - Allen, TX',29928,'Reliant HH - Allen, TX',177,'Reliant & Virginia''s Hospices',267,'Reliant HH - Allen, TX','Location'),
			(5198,'Reliant HH - Conroe, TX',2418,'Reliant HH - Conroe, TX',177,'Reliant & Virginia''s Hospices',265,'Reliant HH - Conroe, TX','Location'),
			(5199,'Good Shepherd - Dallas, TX',29932,'Good Shepherd - Dallas, TX',93,'Good Shepherd Hospice, LLC',148,'Good Shepherd - Dallas, TX','Location'),
			(5200,'Good Shepherd - San Antonio, TX',29934,'Good Shepherd - San Antonio, TX',93,'Good Shepherd Hospice, LLC',149,'Good Shepherd - San Antonio, TX','Location'),
			(5202,'Transcend - San Antonio (South), TX',31027,'Transcend - San Antonio (South), TX',248,'Transitions Hospice, LLC (TX)',513,'Transcend - San Antonio (South), TX','Location'),
			(5203,'SS) Amedisys AseraCare - Stockton, CA (TPA)',32722,'Amedisys AseraCare - Stockton, CA (TPA)',312,'Amedisys AseraCare',587,'Amedisys AseraCare - Stockton, CA (TPA)','Location'),
			(5204,'SS) Amedisys AseraCare - Fresno, CA (TPA)',32723,'Amedisys AseraCare - Fresno, CA (TPA)',312,'Amedisys AseraCare',588,'Amedisys AseraCare - Fresno, CA (TPA)','Location'),
			(5205,'Hope - Bulverde, TX',31025,'Hope - Bulverde, TX',110,'Hope Hospice (TX)',179,'Hope - Bulverde, TX','Location'),
			(5211,'SS) Aspire - Ada, OK',null,null,null,null,null,null,null),
			(5212,'SS) Aspire - Chickasha, OK',null,null,null,null,null,null,null),
			(5217,'SS) Aspire - Shawnee, OK',null,null,null,null,null,null,null),
			(5219,'Bellevue (LTC) - Oklahoma City, OK',3939,'Bellevue (LTC) - Oklahoma City, OK',51,'Bellevue Health & Rehabilitation Center',80,'Bellevue (LTC) - Oklahoma City, OK','Location'),
			(5220,'Bellevue (SNF) - Oklahoma City, OK',3940,'Bellevue (SNF) - Oklahoma City, OK',51,'Bellevue Health & Rehabilitation Center',81,'Bellevue (SNF) - Oklahoma City, OK','Location'),
			(5224,'Concordia (SNF) - Oklahoma City, OK',3921,'Concordia (SNF) - Oklahoma City, OK',71,'Concordia Life Care Community',119,'Concordia (SNF) - Oklahoma City, OK','Location'),
			(5230,'Halo - Ada, OK',3864,'Halo - Ada, OK',99,'Halo Hospice (dba)',155,'Halo - Ada, OK','Location'),
			(5238,'LifeSpring - Norman, OK',3886,'LifeSpring - Norman, OK',137,'LifeSpring In-Home Care Network, LLC',212,'LifeSpring - Norman, OK','Location'),
			(5239,'Mercy - Oklahoma City, OK',3900,'Mercy - Oklahoma City, OK',146,'Mercy Hospice (dba)',221,'Mercy - Oklahoma City, OK','Location'),
			(5241,'SS) Traditions - Chandler, OK',47613,'Traditions - Chandler, OK',161,'Physicians Choice In Care, LLC - Traditions',696,'Traditions - Chandler, OK','Location'),
			(5242,'SS) Traditions - Edmond, OK',null,null,null,null,null,null,null),
			(5243,'SS) Traditions - Tulsa, OK',null,null,null,null,null,null,null),
			(5244,'Sooner - Edmond, OK',3915,'Sooner - Edmond, OK',189,'Sooner Hospice, LLC',285,'Sooner - Edmond, OK','Location'),
			(5246,'Russell-Murray - El Reno, OK',3910,'Russell-Murray - El Reno, OK',179,'Russell-Murray Hospice, Inc',270,'Russell-Murray - El Reno, OK','Location'),
			(5247,'Russell-Murray - Kingfisher, OK',3912,'Russell-Murray - Kingfisher, OK',179,'Russell-Murray Hospice, Inc',272,'Russell-Murray - Kingfisher, OK','Location'),
			(5248,'Russell-Murray - Oklahoma City, OK',3911,'Russell-Murray - Oklahoma City, OK',179,'Russell-Murray Hospice, Inc',271,'Russell-Murray - Oklahoma City, OK','Location'),
			(5249,'Russell-Murray - Weatherford, OK',3913,'Russell-Murray - Weatherford, OK',179,'Russell-Murray Hospice, Inc',273,'Russell-Murray - Weatherford, OK','Location'),
			(5255,'TenderCare (OK) - Norman, OK',3917,'TenderCare (OK) - Norman, OK',240,'TenderCare Hospice (dba)',491,'TenderCare (OK) - Norman, OK','Location'),
			(5256,'Valir - Oklahoma City, OK',3919,'Valir - Oklahoma City, OK',252,'Valir Hospice Care, LLC',519,'Valir - Oklahoma City, OK','Location'),
			(5258,'Oklahoma P&HC - Oklahoma City, OK',30973,'Oklahoma P&HC - Oklahoma City, OK',153,'Oklahoma Palliative & Hospice Care (dba)',228,'Oklahoma P&HC - Oklahoma City, OK','Location'),
			(5259,'Professional HS - North Hollywood, CA',30993,'Professional HS - North Hollywood, CA',165,'Professional Hospice Services, Inc',243,'Professional HS - North Hollywood, CA','Location'),
			(5273,'Encompass - Oklahoma City, OK',3855,'Encompass - Oklahoma City, OK',213,'Encompass Home Health, Inc',389,'Encompass - Oklahoma City, OK','Location'),
			(5274,'SS) All Saints - Rancho Cucamonga, CA',31288,'All Saints - Rancho Cucamonga, CA',19,'All Saints Hospice, Inc (dba)',27,'All Saints - Rancho Cucamonga, CA','Location'),
			(5276,'HS - Internal Use Only',null,null,null,null,null,null,null),
			(5277,'SS) Compassus - Kennesaw, GA',2773,'Compassus - Kennesaw, GA',216,'Hospice Compassus, Inc',411,'Compassus - Kennesaw, GA','Location'),
			(5278,'Transcend - Corpus Christi (South), TX',31233,'Transcend - Corpus Christi (South), TX',248,'Transitions Hospice, LLC (TX)',514,'Transcend - Corpus Christi (South), TX','Location'),
			(5282,'Mt Olive - San Dimas, CA',31254,'Mt Olive - San Dimas, CA',149,'Mt Olive Hospice & Palliative Care (dba)',224,'Mt Olive - San Dimas, CA','Location'),
			(5283,'Instant Care - Van Nuys, CA',31258,'Instant Care - Van Nuys, CA',125,'Instant Care Hospice, Inc',200,'Instant Care - Van Nuys, CA','Location'),
			(5286,'SS) Encompass - El Paso, TX',31409,'Encompass - El Paso, TX',213,'Encompass Home Health, Inc',390,'Encompass - El Paso, TX','Location'),
			(5288,'SS) Kindred - Bellaire (Houston), TX',31425,'Kindred - Bellaire (Houston), TX',219,'Kindred Healthcare, Inc',431,'Kindred - Bellaire (Houston), TX','Location'),
			(5289,'SS) Kindred - El Paso, TX',31428,'Kindred - El Paso, TX',219,'Kindred Healthcare, Inc',427,'Kindred - El Paso, TX','Location'),
			(5291,'SS) Kindred - Mineral Wells (Cleburne), TX',31426,'Kindred - Mineral Wells (Cleburne), TX',219,'Kindred Healthcare, Inc',429,'Kindred - Mineral Wells (Cleburne), TX','Location'),
			(5292,'SS) Kindred - Corpus Christi, TX',31427,'Kindred - Corpus Christi, TX',219,'Kindred Healthcare, Inc',428,'Kindred - Corpus Christi, TX','Location'),
			(5293,'Amenity - Los Angeles, CA',31299,'Amenity - Los Angeles, CA',28,'Amenity Hospice Care of Los Angeles, Inc',42,'Amenity - Los Angeles, CA','Location'),
			(5294,'Reliant HH - Teague, TX',31302,'Reliant HH - Teague, TX',177,'Reliant & Virginia''s Hospices',268,'Reliant HH - Teague, TX','Location'),
			(5297,'Dignity - Nassau Bay, TX',31416,'Dignity - Nassau Bay, TX',79,'Dignity Hospice, LLC',132,'Dignity - Nassau Bay, TX','Location'),
			(5299,'SS) Kindred - Harlingen (Brownsville), TX',31418,'Kindred - Harlingen (Brownsville), TX',219,'Kindred Healthcare, Inc',433,'Kindred - Harlingen (Brownsville), TX','Location'),
			(5300,'SS) Kindred - Beaumont, TX',31419,'Kindred - Beaumont, TX',219,'Kindred Healthcare, Inc',432,'Kindred - Beaumont, TX','Location'),
			(5301,'Chosen NTX - McKinney, TX',null,null,null,null,null,null,null),
			(5302,'SS) Kindred - Temple, TX',31505,'Kindred - Temple, TX',219,'Kindred Healthcare, Inc',448,'Kindred - Temple, TX','Location'),
			(5304,'Faith Presbyterian - Dallas, TX',31470,'Faith Presbyterian - Dallas, TX',87,'Faith Presbyterian Hospice (dba)',141,'Faith Presbyterian - Dallas, TX','Location'),
			(5305,'SS) Amedisys - Temple (SA-T), TX',31503,'Amedisys - Temple (SA-T), TX',200,'Amedisys, Inc',314,'Amedisys - Temple (SA-T), TX','Location'),
			(5306,'SS) Amedisys - Waco (SA-W), TX',31504,'Amedisys - Waco (SA-W), TX',200,'Amedisys, Inc',313,'Amedisys - Waco (SA-W), TX','Location'),
			(5307,'Affinity - Beaumont, TX',31501,'Affinity - Beaumont, TX',16,'Affinity Hospice, LLC',24,'Affinity - Beaumont, TX','Location'),
			(5309,'Tapestry - Kennesaw, GA',31520,'Tapestry - Kennesaw, GA',239,'Tapestry Hospice of Northwest Georgia',488,'Tapestry - Kennesaw, GA','Location'),
			(5310,'Tapestry - Ringgold, GA',31522,'Tapestry - Ringgold, GA',239,'Tapestry Hospice of Northwest Georgia',489,'Tapestry - Ringgold, GA','Location'),
			(5313,'Bristol - Sacramento, CA',null,null,null,null,null,null,null),
			(5317,'Olive Branch - Jasper, TX',31530,'Olive Branch - Jasper, TX',154,'Olive Branch Hospice (dba)',229,'Olive Branch - Jasper, TX','Location'),
			(5318,'Kindred - Austin, TX',31539,'Kindred - Austin, TX',219,'Kindred Healthcare, Inc',449,'Kindred - Austin, TX','Location'),
			(5319,'Aberdeen - Roswell, GA',31627,'Aberdeen - Roswell, GA',12,'Aberdeen Place Hospice, Inc',13,'Aberdeen - Roswell, GA','Location'),
			(5320,'HealthFlex - Burlingame, CA',31599,'HealthFlex - Burlingame, CA',102,'HealthFlex Hospice',165,'HealthFlex - Burlingame, CA','Location'),
			(5321,'Amedisys - CCH San Marcos, TX',31616,'Amedisys - CCH San Marcos, TX',200,'Amedisys, Inc',312,'Amedisys - CCH San Marcos, TX','Location'),
			(5322,'SS) Amedisys - CCH Houston, TX',31617,'Amedisys - CCH Houston, TX',200,'Amedisys, Inc',311,'Amedisys - CCH Houston, TX','Location'),
			(5323,'SS) Amedisys - CCH Conroe, TX',31618,'Amedisys - CCH Conroe, TX',200,'Amedisys, Inc',310,'Amedisys - CCH Conroe, TX','Location'),
			(5324,'SS) Amedisys - CCH Los Angeles, CA',31619,'Amedisys - CCH Los Angeles, CA',200,'Amedisys, Inc',309,'Amedisys - CCH Los Angeles, CA','Location'),
			(5328,'Q) Legacy - Decatur, GA',31626,'Legacy - Decatur, GA',175,'Legacy Hospice, LLC',262,'Legacy - Decatur, GA','Location'),
			(5330,'Abella Palliative Care - Calhoun, GA',31672,'Abella Palliative Care - Calhoun, GA',239,'Tapestry Hospice of Northwest Georgia',490,'Abella Palliative Care - Calhoun, GA','Location'),
			(5331,'Bristol - Redding, CA',31629,'Bristol - Redding, CA',54,'Bristol Hospice LLC',85,'Bristol - Redding, CA','Location'),
			(5332,'San Antonio HC - San Antonio, TX',31667,'San Antonio HC - San Antonio, TX',183,'San Antonio Hospice',279,'San Antonio HC - San Antonio, TX','Location'),
			(5333,'1st Choice - Huntsville, TX',31669,'1st Choice - Huntsville, TX',5,'1st Choice Hospice, LLC',5,'1st Choice - Huntsville, TX','Location'),
			(5334,'SS) Amedisys - CCH Athens, GA',31704,'Amedisys - CCH Athens, GA',200,'Amedisys, Inc',306,'Amedisys - CCH Athens, GA','Location'),
			(5336,'SS) Amedisys - CCH Macon, GA',31701,'Amedisys - CCH Macon, GA',200,'Amedisys, Inc',307,'Amedisys - CCH Macon, GA','Location'),
			(5337,'SS) Traditions - Longview, TX',31737,'Traditions - Longview, TX',233,'Traditions Hospice (dba)',478,'Traditions - Longview, TX','Location'),
			(5340,'Beaumont HH&H (dba) - Madison Heights, MI',31742,'Beaumont HH&H (dba) - Madison Heights, MI',22,'Alternate Solutions Health Network, LLC',30,'Beaumont HH&H (dba) - Madison Heights, MI','Location'),
			(5342,'SS) Compassus - Huntsville, TX',31738,'Compassus - Huntsville, TX',216,'Hospice Compassus, Inc',414,'Compassus - Huntsville, TX','Location'),
			(5346,'Heritage - Sulphur Springs, TX',31740,'Heritage - Sulphur Springs, TX',103,'Heritage Hospice (E TX)',167,'Heritage - Sulphur Springs, TX','Location'),
			(5347,'Bristol - San Diego, CA',31769,'Bristol - San Diego, CA',54,'Bristol Hospice LLC',86,'Bristol - San Diego, CA','Location'),
			(5348,'SS) Affinity - Canton, GA',31785,'Affinity - Canton, GA',199,'Affinity Acquisitions Georgia, LLC',301,'Affinity - Canton, GA','Location'),
			(5349,'Good Samaritan Society - Fort Worth, TX',31787,'Good Samaritan Society - Fort Worth, TX',62,'Good Samaritan HCBS TX, LLC (2)',168,'Good Samaritan Society - Fort Worth, TX','Location'),
			(5350,'Total H&PC - Ft Worth, TX',31804,'Total H&PC - Ft Worth, TX',243,'Three Oaks Hospice, Inc',495,'Total H&PC - Ft Worth, TX','Location'),
			(5351,'Samaritan - Marlton, NJ',31806,'Samaritan - Marlton, NJ',182,'Samaritan Healthcare & Hospice, Inc',276,'Samaritan - Marlton, NJ','Location'),
			(5352,'Samaritan IPU - Voorhees, NJ',31808,'Samaritan IPU - Voorhees, NJ',182,'Samaritan Healthcare & Hospice, Inc',278,'Samaritan IPU - Voorhees, NJ','Location'),
			(5353,'Samaritan IPU - Mt Holly, NJ',31807,'Samaritan IPU - Mt Holly, NJ',182,'Samaritan Healthcare & Hospice, Inc',277,'Samaritan IPU - Mt Holly, NJ','Location'),
			(5354,'Capital City - Columbus, OH',31821,'Capital City - Columbus, OH',176,'Queen City Hospice, LLC',264,'Capital City - Columbus, OH','Location'),
			(5356,'Queen City - Mason, OH',31820,'Queen City - Mason, OH',176,'Queen City Hospice, LLC',263,'Queen City - Mason, OH','Location'),
			(5357,'Supportive HC - Upland, CA',31810,'Supportive HC - Upland, CA',2,'A to Z Hospice Care, Inc',2,'Supportive HC - Upland, CA','Location'),
			(5358,'Prime Care - Longview, TX',31815,'Prime Care - Longview, TX',163,'Prime Care Hospice, LLC',241,'Prime Care - Longview, TX','Location'),
			(5359,'Grace and Hope - Van Nuys, CA',31851,'Grace and Hope - Van Nuys, CA',94,'Grace and Hope Hospice, Inc',150,'Grace and Hope - Van Nuys, CA','Location'),
			(5360,'Q) Hope HC - Garland, TX',31855,'Hope HC - Garland, TX',167,'Boerne Hospice Partners, LLC',245,'Hope HC - Garland, TX','Location'),
			(5362,'Q) Crossroads H&PC - Atlanta (Team A), GA',31860,'Crossroads H&PC - Atlanta (Team A), GA',206,'Crossroads Hospice & Palliative Care (dba)',334,'Crossroads H&PC - Atlanta (Team A), GA','Location'),
			(5363,'SS) Crossroads H&PC - Oklahoma City, OK',31861,'Crossroads H&PC - Oklahoma City, OK',206,'Crossroads Hospice & Palliative Care (dba)',335,'Crossroads H&PC - Oklahoma City, OK','Location'),
			(5365,'SS) Northeast Georgia MC - Gainesville, GA',31909,'Northeast Georgia MC - Gainesville, GA',225,'Northeast Georgia MC',457,'Northeast Georgia MC - Gainesville, GA','Location'),
			(5366,'SS) AccentCare (Texas HHH) - Houston, TX',31897,'AccentCare (Texas HHH) - Houston, TX',197,'AccentCare (Texas HHH)',293,'AccentCare (Texas HHH) - Houston, TX','Location'),
			(5368,'SS) Helping Hands - San Mateo, CA',31912,'Helping Hands - San Mateo, CA',214,'Helping Hands Home Health Care & Hospice, Inc',391,'Helping Hands - San Mateo, CA','Location'),
			(5373,'SS) AccentCare (Texas HHH) - Beaumont, TX',31898,'AccentCare (Texas HHH) - Beaumont, TX',197,'AccentCare (Texas HHH)',294,'AccentCare (Texas HHH) - Beaumont, TX','Location'),
			(5374,'SS) AccentCare (Texas HHH) - College Station, TX',31899,'AccentCare (Texas HHH) - College Station, TX',197,'AccentCare (Texas HHH)',295,'AccentCare (Texas HHH) - College Station, TX','Location'),
			(5376,'SS) AccentCare (Texas HHH) - Waco, TX',31901,'AccentCare (Texas HHH) - Waco, TX',197,'AccentCare (Texas HHH)',296,'AccentCare (Texas HHH) - Waco, TX','Location'),
			(5377,'Resolutions Hospice - Austin, TX',31920,'Resolutions Hospice - Austin, TX',178,'Resolutions Hospice',269,'Resolutions Hospice - Austin, TX','Location'),
			(5380,'Merit - Dallas, TX',31916,'Merit - Dallas, TX',147,'Merit Hospice, LLC',222,'Merit - Dallas, TX','Location'),
			(5381,'Three Oaks - San Antonio, TX',31962,'Three Oaks - San Antonio, TX',243,'Three Oaks Hospice, Inc',496,'Three Oaks - San Antonio, TX','Location'),
			(5382,'One Point - Dallas, TX',null,null,null,null,null,null,null),
			(5385,'Precious - Fayetteville, GA',31972,'Precious - Fayetteville, GA',3,'Precious Hospice, LLC',3,'Precious - Fayetteville, GA','Location'),
			(5386,'Symponia - Decatur, GA (SPA)',31974,'Symponia - Decatur, GA (SPA)',238,'Symponia Hospice, Inc',486,'Symponia - Decatur, GA (SPA)','Location'),
			(5387,'Absolute - North Canton, OH',31981,'Absolute - North Canton, OH',14,'Absolute Hospice, Inc',15,'Absolute - North Canton, OH','Location'),
			(5388,'Hamilton - Dalton, GA',31988,'Hamilton - Dalton, GA',100,'Hamilton Hospice (dba)',156,'Hamilton - Dalton, GA','Location'),
			(5389,'SS) AccentCare (Texas HHH) - Killeen, TX',31998,'AccentCare (Texas HHH) - Killeen, TX',197,'AccentCare (Texas HHH)',297,'AccentCare (Texas HHH) - Killeen, TX','Location'),
			(5390,'Absolute - Caldwell, OH',31984,'Absolute - Caldwell, OH',14,'Absolute Hospice, Inc',16,'Absolute - Caldwell, OH','Location'),
			(5391,'Absolute - Cleveland, OH',31985,'Absolute - Cleveland, OH',14,'Absolute Hospice, Inc',17,'Absolute - Cleveland, OH','Location'),
			(5392,'Absolute - Columbus, OH',31986,'Absolute - Columbus, OH',14,'Absolute Hospice, Inc',18,'Absolute - Columbus, OH','Location'),
			(5395,'Echo - Orange, CA',null,null,null,null,null,null,null),
			(5396,'Millennium - Spring, TX',2313,'Millennium - Spring, TX',47,'Avatar & Millennium Agencies',75,'Millennium - Spring, TX','Location'),
			(5398,'Arden HC - Glendale, CA',32053,'Arden HC - Glendale, CA',38,'Arden Hospice Care, Inc.',53,'Arden HC - Glendale, CA','Location'),
			(5399,'Suncrest - Walnut Creek, CA',32050,'Suncrest - Walnut Creek, CA',237,'Suncrest Hospice',484,'Suncrest - Walnut Creek, CA','Location'),
			(5400,'Suncrest - San Jose, CA',32051,'Suncrest - San Jose, CA',237,'Suncrest Hospice',485,'Suncrest - San Jose, CA','Location'),
			(5401,'Three Oaks - Houston, TX',32074,'Three Oaks - Houston, TX',243,'Three Oaks Hospice, Inc',498,'Three Oaks - Houston, TX','Location'),
			(5402,'Peace - Three Oaks - Chicago, IL',32073,'Peace - Three Oaks - Chicago, IL',243,'Three Oaks Hospice, Inc',497,'Peace - Three Oaks - Chicago, IL','Location'),
			(5403,'Divinis Care - Dallas, TX',32055,'Divinis Care - Dallas, TX',80,'Divinis Care Hospice',133,'Divinis Care - Dallas, TX','Location'),
			(5405,'A-Med - Corpus Christi, TX',32061,'A-Med - Corpus Christi, TX',11,'A-Med Health, Inc',12,'A-Med - Corpus Christi, TX','Location'),
			(5406,'Moonlight HC - Burbank, CA',32104,'Moonlight HC - Burbank, CA',148,'Moonlight Hospice Care, Inc',223,'Moonlight HC - Burbank, CA','Location'),
			(5407,'Mercy - Canton, OH',31993,'Mercy - Canton, OH',22,'Alternate Solutions Health Network, LLC',32,'Mercy - Canton, OH','Location'),
			(5408,'Summa - Akron, OH',31992,'Summa - Akron, OH',22,'Alternate Solutions Health Network, LLC',31,'Summa - Akron, OH','Location'),
			(5409,'Standard - Cameron, TX',32106,'Standard - Cameron, TX',196,'Standard Hospice Inc.',292,'Standard - Cameron, TX','Location'),
			(5411,'Aadi HH and H - Corpus Christi, TX',32116,'Aadi HH and H - Corpus Christi, TX',49,'Bayside Solutions Inc. dba Aadi Home Health and Hospice',78,'Aadi HH and H - Corpus Christi, TX','Location'),
			(5412,'SS) Amedisys - CCH Laguna Niguel, CA ',null,null,null,null,null,null,null),
			(5413,'Humanity - Edmond, OK',32150,'Humanity - Edmond, OK',121,'Humanity Hospice',193,'Humanity - Edmond, OK','Location'),
			(5414,'Humanity - Tulsa, OK',32152,'Humanity - Tulsa, OK',121,'Humanity Hospice',195,'Humanity - Tulsa, OK','Location'),
			(5415,'Humanity - Ponca City, OK',32151,'Humanity - Ponca City, OK',121,'Humanity Hospice',194,'Humanity - Ponca City, OK','Location'),
			(5416,'Humanity - Woodward, OK (TPP)',32153,'Humanity - Woodward, OK (TPP)',121,'Humanity Hospice',196,'Humanity - Woodward, OK (TPP)','Location'),
			(5417,'VNA - Kansas City, MO',32515,'VNA - Kansas City, MO',256,'VNA Corporation,DBA Visiting Nurse Association',526,'VNA - Kansas City, MO','Location'),
			(5418,'Three Oaks - Overland Park, KS',32158,'Three Oaks - Overland Park, KS',243,'Three Oaks Hospice, Inc',501,'Three Oaks - Overland Park, KS','Location'),
			(5419,'Three Oaks - St Joseph, MO',32159,'Three Oaks - St Joseph, MO',243,'Three Oaks Hospice, Inc',502,'Three Oaks - St Joseph, MO','Location'),
			(5420,'Three Oaks - Kansas City, MO',32140,'Three Oaks - Kansas City, MO',243,'Three Oaks Hospice, Inc',499,'Three Oaks - Kansas City, MO','Location'),
			(5421,'Generations - Austin, TX',32118,'Generations - Austin, TX',91,'Generations Health Care, INC',146,'Generations - Austin, TX','Location'),
			(5422,'Yellow Rose - San Antonio, TX',32121,'Yellow Rose - San Antonio, TX',258,'Yellow Rose Hospice, INC',528,'Yellow Rose - San Antonio, TX','Location'),
			(5425,'A Caring Touch - Lufkin, TX',32123,'A Caring Touch - Lufkin, TX',254,'Venture I, INC dba A Caring Touch Home Health Services & Hospice Care',521,'A Caring Touch - Lufkin, TX','Location'),
			(5426,'Desert View - Victorville, CA',32157,'Desert View - Victorville, CA',77,'Desert View Hospice, INC',130,'Desert View - Victorville, CA','Location'),
			(5427,'GHC - Upland, CA',32155,'GHC - Upland, CA',92,'GHC Hospice, INC',147,'GHC - Upland, CA','Location'),
			(5428,'Three Oaks - AMed - Austin, TX',32160,'Three Oaks - AMed - Austin, TX',243,'Three Oaks Hospice, Inc',503,'Three Oaks - AMed - Austin, TX','Location'),
			(5429,'Total H&PC - Denton, TX',32144,'Total H&PC - Denton, TX',243,'Three Oaks Hospice, Inc',500,'Total H&PC - Denton, TX','Location'),
			(5432,'Tapestry - Fort Oglethorpe, GA',41907,'Tapestry - Fort Oglethorpe, GA',239,'Tapestry Hospice of Northwest Georgia',677,'Tapestry - Fort Oglethorpe, GA','Location'),
			(5433,'SS) Affinity - Stockbridge , GA',32170,'Affinity - Stockbridge , GA',199,'Affinity Acquisitions Georgia, LLC',302,'Affinity - Stockbridge , GA','Location'),
			(5434,'SS) Affinity - Marietta , GA',32171,'Affinity - Marietta , GA',199,'Affinity Acquisitions Georgia, LLC',303,'Affinity - Marietta , GA','Location'),
			(5435,'SS) Affinity - Lawrenceville , GA',32172,'Affinity - Lawrenceville , GA',199,'Affinity Acquisitions Georgia, LLC',304,'Affinity - Lawrenceville , GA','Location'),
			(5436,'Merciful Hands - Houston, TX',32495,'Merciful Hands - Houston, TX',37,'Arcturus Healthcare, LLC',52,'Merciful Hands - Houston, TX','Location'),
			(5437,'Three Oaks - El Paso, TX',32182,'Three Oaks - El Paso, TX',243,'Three Oaks Hospice, Inc',504,'Three Oaks - El Paso, TX','Location'),
			(5439,'SS) AccentCare (Texas HHH) - Sugarland, TX',32493,'AccentCare (Texas HHH) - Sugarland, TX',197,'AccentCare (Texas HHH)',299,'AccentCare (Texas HHH) - Sugarland, TX','Location'),
			(5440,'SS) AccentCare (Texas HHH) - Cleveland, TX',32492,'AccentCare (Texas HHH) - Cleveland, TX',197,'AccentCare (Texas HHH)',298,'AccentCare (Texas HHH) - Cleveland, TX','Location'),
			(5441,'SS) Compassus - Waco, TX',32494,'Compassus - Waco, TX',216,'Hospice Compassus, Inc',415,'Compassus - Waco, TX','Location'),
			(5442,'Q) Hospice of Michigan',32516,'Hospice of Michigan',174,'Qualis Management, LLC',260,'Hospice of Michigan','Location'),
			(5443,'Maximum Quality - Weslaco, TX',32549,'Maximum Quality - Weslaco, TX',145,'Maximum Quality Hospice, LLC',220,'Maximum Quality - Weslaco, TX','Location'),
			(5445,'R2R Palliative & HC - Lewisville, TX',32703,'R2R Palliative & HC - Lewisville, TX',310,'R2R Palliative & Hospice Care, LLC',582,'R2R Palliative & HC - Lewisville, TX','Location'),
			(5446,'SS) Amedisys - CCH Madison, GA',32536,'Amedisys - CCH Madison, GA',200,'Amedisys, Inc',324,'Amedisys - CCH Madison, GA','Location'),
			(5448,'Snowline - Diamond Springs, CA',33324,'Snowline - Diamond Springs, CA',304,'Snowline Hospice of El Dorado CO., INC',574,'Snowline - Diamond Springs, CA','Location'),
			(5449,'A Plus - Pleasanton, CA',32828,'A Plus - Pleasanton, CA',9,'A Plus Hospice, INC',580,'A Plus - Pleasanton, CA','Location'),
			(5450,'VNA - Salinas, CA',33329,'VNA - Salinas, CA',309,'VNA Hospice',579,'VNA - Salinas, CA','Location'),
			(5451,'Hospice of Central Coast - Monterey, CA',32832,'Hospice of Central Coast - Monterey, CA',293,'Hospice of the Central Coast',563,'Hospice of Central Coast - Monterey, CA','Location'),
			(5452,'Butte HH & H - Chico, CA',32829,'Butte HH & H - Chico, CA',276,'Butte Home Health & Hospice',546,'Butte HH & H - Chico, CA','Location'),
			(5453,'Freedom HH & H - Marysville, CA',33306,'Freedom HH & H - Marysville, CA',287,'Freedom Home Health & Hospice',557,'Freedom HH & H - Marysville, CA','Location'),
			(5454,'Green Valley - Roseville, CA',32831,'Green Valley - Roseville, CA',289,'Green Valley Hospice',559,'Green Valley - Roseville, CA','Location'),
			(5455,'Careplus - Livermore, CA',32830,'Careplus - Livermore, CA',279,'Careplus Hospice Services, Inc.',549,'Careplus - Livermore, CA','Location'),
			(5456,'Angels - Castro Valley, CA',32827,'Angels - Castro Valley, CA',269,'Angels Hospice, LLC',539,'Angels - Castro Valley, CA','Location'),
			(5458,'Caremust HHC & HS - San Jose, CA',33296,'Caremust HHC & HS - San Jose, CA',278,'Caremust Home Health Care & Hospice Services',548,'Caremust HHC & HS - San Jose, CA','Location'),
			(5459,'Central Valley - Modesto, CA',33299,'Central Valley - Modesto, CA',281,'Central Valley Hospice',551,'Central Valley - Modesto, CA','Location'),
			(5460,'Lifecare Solutions - Newark, CA',33314,'Lifecare Solutions - Newark, CA',295,'LifeCare Solutions Palliative and Hospice, LLC',565,'Lifecare Solutions - Newark, CA','Location'),
			(5461,'Colusa MC - Colusa, CA',33300,'Colusa MC - Colusa, CA',282,'Colusa Medical Center, LLC',552,'Colusa MC - Colusa, CA','Location'),
			(5463,'American H & HH - Dublin, CA',33282,'American H & HH - Dublin, CA',265,'American Hospice & Home Health',535,'American H & HH - Dublin, CA','Location'),
			(5464,'Caring Heart - Brentwood, CA',33298,'Caring Heart - Brentwood, CA',280,'Caring Heart Hospice, Inc.',550,'Caring Heart - Brentwood, CA','Location'),
			(5465,'Grace and Glory - Antioch, CA',33308,'Grace and Glory - Antioch, CA',314,'Grace and Glory Hospice, Inc.',592,'Grace and Glory - Antioch, CA','Location'),
			(5466,'Oak Creek - Folsom, CA',33320,'Oak Creek - Folsom, CA',300,'Oak Creek Hospice',570,'Oak Creek - Folsom, CA','Location'),
			(5467,'Partners in Care - Auburn, CA',33321,'Partners in Care - Auburn, CA',301,'Partners in Care Senior Care',571,'Partners in Care - Auburn, CA','Location'),
			(5468,'Star Care - San Jose, CA',33326,'Star Care - San Jose, CA',306,'Star Care Hospice',576,'Star Care - San Jose, CA','Location'),
			(5470,'American Heritage - Folsom, CA',33283,'American Heritage - Folsom, CA',313,'American Heritage Hospice, Inc.',591,'American Heritage - Folsom, CA','Location'),
			(5471,'MD Choice - Concord, CA',33315,'MD Choice - Concord, CA',296,'MD Choice Hospice, Inc.',566,'MD Choice - Concord, CA','Location'),
			(5472,'Norcal - Lathrop, CA',33319,'Norcal - Lathrop, CA',299,'Norcal Hospice, Inc.',569,'Norcal - Lathrop, CA','Location'),
			(5473,'Universal Health Net - Monterey, CA',33328,'Universal Health Net - Monterey, CA',308,'Universal Health Net Monterey, Inc.',578,'Universal Health Net - Monterey, CA','Location'),
			(5474,'Angel PC & H - South San Francisco, CA',33286,'Angel PC & H - South San Francisco, CA',268,'Angel Palliative Care and Hospice',538,'Angel PC & H - South San Francisco, CA','Location'),
			(5475,'Ardent - Hayward, CA',33288,'Ardent - Hayward, CA',270,'Ardent Hospice Services, Inc.',540,'Ardent - Hayward, CA','Location'),
			(5476,'Big Hearts - Sacramento, CA',33293,'Big Hearts - Sacramento, CA',275,'Big Hearts Hospice Care, Inc.',545,'Big Hearts - Sacramento, CA','Location'),
			(5478,'True Care - Carmichael, CA',33327,'True Care - Carmichael, CA',307,'True Care Hospice of Northern California',577,'True Care - Carmichael, CA','Location'),
			(5479,'A Plus - Sacramento, CA',33279,'A Plus - Sacramento, CA',8,'A Plus Healthcare Home Health Agency',581,'A Plus - Sacramento, CA','Location'),
			(5480,'NeoGen - Hayward, CA',33317,'NeoGen - Hayward, CA',298,'NeoGen Care',568,'NeoGen - Hayward, CA','Location'),
			(5481,'Melodia - Fremont, CA',33316,'Melodia - Fremont, CA',297,'Melodia Care, Inc. DBA Melodia Hospice',567,'Melodia - Fremont, CA','Location'),
			(5482,'First Choice - Foster City, CA',33305,'First Choice - Foster City, CA',286,'First Choice Home Health Care & Hospice, Inc.',556,'First Choice - Foster City, CA','Location'),
			(5483,'Capitol - Elk Grove, CA',33295,'Capitol - Elk Grove, CA',277,'Capitol Health Care Inc. DBA Capitol Hospice',547,'Capitol - Elk Grove, CA','Location'),
			(5484,'Healthcare California - Fresno, CA',40487,'Healthcare California - Fresno, CA',320,'Healthcare California Home Health & Hospice',623,'Healthcare California - Fresno, CA','Location'),
			(5485,'Attaie - Pleasanton, CA',33291,'Attaie - Pleasanton, CA',273,'Attaie Hospice',543,'Attaie - Pleasanton, CA','Location'),
			(5486,'Solano Care - Vallejo, CA',32705,'Solano Care - Vallejo, CA',188,'Solano Care',284,'Solano Care - Vallejo, CA','Location'),
			(5487,'HC) First Call - Martinez, CA',40492,'First Call - Martinez, CA',317,'First Call Hospice',616,'First Call - Martinez, CA','Location'),
			(5490,'Adventist Health - Sonora, CA',33032,'Adventist Health - Sonora, CA',261,'Adventist Health Lodi Memorial and Sonora Regional Medical Center',531,'Adventist Health - Sonora, CA','Location'),
			(5491,'Crossroads - Oakland, CA',33301,'Crossroads - Oakland, CA',283,'Crossroads Home Health & Hospice',553,'Crossroads - Oakland, CA','Location'),
			(5492,'SS) Brookdale - Sacramento , CA',40355,'Brookdale - Sacramento , CA',204,'Brookdale Senior Living, Inc',602,'Brookdale - Sacramento , CA','Location'),
			(5493,'SS) Gentiva - Bakersfield, CA',40356,'Gentiva - Bakersfield, CA',219,'Kindred Healthcare, Inc',596,'Gentiva - Bakersfield, CA','Location'),
			(5496,'Amore - Oakland, CA',33285,'Amore - Oakland, CA',267,'Amore Hospice Inc.',537,'Amore - Oakland, CA','Location'),
			(5497,'SS) Gentiva - Tulare, CA',40357,'Gentiva - Tulare, CA',219,'Kindred Healthcare, Inc',597,'Gentiva - Tulare, CA','Location'),
			(5499,'SS) Sutter - San Mateo, CA',40360,'Sutter - San Mateo, CA',230,'Sutter Care at Home (dba)',600,'Sutter - San Mateo, CA','Location'),
			(5500,'SS) Sutter - Santa Rosa, CA',40361,'Sutter - Santa Rosa, CA',230,'Sutter Care at Home (dba)',599,'Sutter - Santa Rosa, CA','Location'),
			(5501,'SS) Sutter - San Francisco, CA',40358,'Sutter - San Francisco, CA',230,'Sutter Care at Home (dba)',598,'Sutter - San Francisco, CA','Location'),
			(5502,'SS) Sutter - San Jose, CA',40359,'Sutter - San Jose, CA',230,'Sutter Care at Home (dba)',601,'Sutter - San Jose, CA','Location'),
			(5503,'SS) Suncrest - Sacramento, CA (TPA)',40380,'Suncrest - Sacramento, CA (TPA)',326,'Suncrest Health Services, LLC',629,'Suncrest - Sacramento, CA (TPA)','Location'),
			(5504,'SS) Suncrest - San Jose, CA',32051,'Suncrest - San Jose, CA',237,'Suncrest Hospice',485,'Suncrest - San Jose, CA','Location'),
			(5505,'VNA Palliative Care - Salinas, CA',33330,'VNA Palliative Care - Salinas, CA',309,'VNA Hospice',594,'VNA Palliative Care - Salinas, CA','Location'),
			(5506,'SS) Adventist Health - Hanford, CA',40370,'Adventist Health - Hanford, CA',316,'Adventist Health',610,'Adventist Health - Hanford, CA','Location'),
			(5507,'SS) Adventist Health - Paradise, CA',40371,'Adventist Health - Paradise, CA',316,'Adventist Health',611,'Adventist Health - Paradise, CA','Location'),
			(5508,'SS) St Agnes HH&H - Fresno, CA',40379,'St Agnes HH&H - Fresno, CA',325,'Trinity Health',628,'St Agnes HH&H - Fresno, CA','Location'),
			(5509,'SS) Mission H&HC - San Mateo, CA',40378,'Mission H&HC - San Mateo, CA',324,'Mission Hospice & Home Care Inc',627,'Mission H&HC - San Mateo, CA','Location'),
			(5510,'SS) Medically Home Group- Hanford, CA',40377,'Medically Home Group- Hanford, CA',323,'Medically Home Group',626,'Medically Home Group- Hanford, CA','Location'),
			(5511,'SS) Hospice by the Bay - Larkspur, CA',40376,'Hospice by the Bay - Larkspur, CA',322,'Hospice by the Bay',625,'Hospice by the Bay - Larkspur, CA','Location'),
			(5512,'SS) Mercy - Red Bluff, CA',40363,'Mercy Hospice - Red Bluff, CA',319,'CHI National Home Care, Inc.',618,'Mercy Hospice - Red Bluff, CA','Location'),
			(5513,'SS) Mercy Hospice - Redding, CA',40364,'Mercy Hospice - Redding, CA',319,'CHI National Home Care, Inc.',619,'Mercy Hospice - Redding, CA','Location'),
			(5514,'SS) Pathways - Oakland, CA',40365,'Pathways - Oakland, CA (TPA)',319,'CHI National Home Care, Inc.',620,'Pathways - Oakland, CA (TPA)','Location'),
			(5515,'SS) Pathways - South San Francisco, CA',40366,'Pathways - South San Francisco, CA (TPA)',319,'CHI National Home Care, Inc.',621,'Pathways - South San Francisco, CA (TPA)','Location'),
			(5516,'SS) Pathways - Sunnyvale, CA',40367,'Pathways - Sunnyvale, CA (TPA)',319,'CHI National Home Care, Inc.',622,'Pathways - Sunnyvale, CA (TPA)','Location'),
			(5517,'AllSupport - Fremont, CA',33030,'AllSupport - Fremont, CA',263,'Allsupport Hospice',533,'AllSupport - Fremont, CA','Location'),
			(5518,'American CM - San Rafeal, CA',33029,'American CM - San Rafeal, CA',264,'American CM Hospice, Inc.',534,'American CM - San Rafeal, CA','Location'),
			(5519,'Armstrong - El Dorado Hills, CA',33289,'Armstrong - El Dorado Hills, CA',271,'Armstrong Hospice',541,'Armstrong - El Dorado Hills, CA','Location'),
			(5520,'Bay HC - San Ramon, CA',33292,'Bay HC - San Ramon, CA',274,'Bay Hospice Care',544,'Bay HC - San Ramon, CA','Location'),
			(5521,'Atrium - Brentwood, CA',33290,'Atrium - Brentwood, CA',272,'Atrium Hospice',542,'Atrium - Brentwood, CA','Location'),
			(5522,'Custom Care HS - Elk Grove, CA',33302,'Custom Care HS - Elk Grove, CA',284,'Custom Care Hospice Services, Inc.',554,'Custom Care HS - Elk Grove, CA','Location'),
			(5524,'Essentials - Hayward, CA',33304,'Essentials - Hayward, CA',294,'Hospicio De San Miguel, Inc dba Essentials Hospice',564,'Essentials - Hayward, CA','Location'),
			(5525,'Health Now HH & H - Hayward, CA',33311,'Health Now HH & H - Hayward, CA',291,'Health Now Home Health & Hospice',561,'Health Now HH & H - Hayward, CA','Location'),
			(5528,'Solace HC - Bakersfield, CA',33325,'Solace HC - Bakersfield, CA',305,'Solace Hospice Care',575,'Solace HC - Bakersfield, CA','Location'),
			(5529,'American Pro - Morgan Hill, CA',33284,'American Pro - Morgan Hill, CA',266,'American Pro Health & Hospice',536,'American Pro - Morgan Hill, CA','Location'),
			(5531,'SS) Adventist Health - Bakersfield, CA',40369,'Adventist Health - Bakersfield, CA',316,'Adventist Health',609,'Adventist Health - Bakersfield, CA','Location'),
			(5532,'Noble - Fremont, CA',33318,'Noble - Fremont, CA',281,'Central Valley Hospice',593,'Noble - Fremont, CA','Location'),
			(5533,'Pinnacle HC - Sacramento, CA',33322,'Pinnacle HC - Sacramento, CA',302,'Pinnacle Home Health & Hospice, dba Pinnacle Hospice Care',572,'Pinnacle HC - Sacramento, CA','Location'),
			(5534,'SS) Adya H & PC - Fairfield, CA',40374,'Adya H & PC - Fairfield, CA',318,'Adya Hospice & Palliative Care, LLC',617,'Adya H & PC - Fairfield, CA','Location'),
			(5536,'SS) Adventist Health - Yuba City, CA',40372,'Adventist Health - Yuba City, CA',316,'Adventist Health',612,'Adventist Health - Yuba City, CA','Location'),
			(5538,'Community First HC - San Antonio, TX2',32127,'Community First - San Antonio, TX',67,'Community First Hospice, INC',102,'Community First - San Antonio, TX','Location'),
			(5539,'Nightingale - San Antonio, TX',32125,'Nightingale - San Antonio, TX',150,'Nightingale Hospice, INC',225,'Nightingale - San Antonio, TX','Location'),
			(5540,'Mission HS - Pleasanton, CA',null,null,null,null,null,null,null),
			(5541,'Amor HC - Houston, TX',42881,'Amor HC - Houston, TX',332,'Amore Hospice Care, Inc.',691,'Amor HC - Houston, TX','Location'),
			(5542,'Q) Caris - Chattanooga, TN',41909,'Caris - Chattanooga, TN',331,'Caris Healthcare, LP',680,'Caris - Chattanooga, TN','Location'),
			(5543,'Q) Caris - Lenoir, TN',null,null,null,null,null,null,null),
			(5544,'Q) Caris - Rossville, GA',null,null,null,null,null,null,null),
			(5545,'Advanced - Hayward, CA',40485,'Advanced - Hayward, CA',15,'Advent Care INC',603,'Advanced - Hayward, CA','Location'),
			(5546,'Holy Hospice & PC - Mesquite, TX',null,null,null,null,null,null,null),
			(5547,'Resolutions - Houston, TX',40046,'Resolutions - Houston, TX',178,'Resolutions Hospice',606,'Resolutions - Houston, TX','Location'),
			(5548,'Gracia - Corpus Christi, TX',null,null,null,null,null,null,null),
			(5549,'St. Marie''s - Southfield, MI',null,null,null,null,null,null,null),
			(5550,'SS) Intrepid - Beaumont, TX',40354,'Intrepid - Beaumont, TX',327,'StateServ Network Services (dba)',650,'Intrepid - Beaumont, TX','Location'),
			(5551,'SS) Affinity - Rome , GA',40049,'Affinity - Rome , GA',199,'Affinity Acquisitions Georgia, LLC',595,'Affinity - Rome , GA','Location'),
			(5553,'Affinity HC - Hayward, CA',42860,'Affinity HC - Hayward, CA',334,'Affinity Hospice Care, Inc. (CA)',693,'Affinity HC - Hayward, CA','Location'),
			(5554,'Westlake - Simi Valley, CA',null,null,null,null,null,null,null),
			(5555,'Gracia - Austin, TX',null,null,null,null,null,null,null),
			(5556,'Topanga HC - Canoga Park, CA',41906,'Topanga HC - Canoga Park, CA',329,'Topanga Hospice Care, Inc.',678,'Topanga HC - Canoga Park, CA','Location'),
			(5557,'Reliant HH - Kingwood, TX',41904,'Reliant HH - Kingwood, TX',177,'Reliant & Virginia''s Hospices',674,'Reliant HH - Kingwood, TX','Location'),
			(5558,'Comfort - Irving, TX',42020,'Comfort - Irving, TX',328,'Comfort Hospice of Texas, LLC',676,'Comfort - Irving, TX','Location'),
			(5559,'SS) The Medical Team - Livonia, MI',null,null,null,null,null,null,null),
			(5560,'Trinity - San Antonio, TX',null,null,null,null,null,null,null),
			(5561,'Trinity - Irving, TX',null,null,null,null,null,null,null),
			(5562,'Trinity - Houston, TX',null,null,null,null,null,null,null),
			(5563,'Trinity - Beaumont, TX',null,null,null,null,null,null,null),
			(5564,'SS) The Medical Team - Corpus Christi, TX',null,null,null,null,null,null,null),
			(5566,'Centric HH & H - Plano, TX',null,null,null,null,null,null,null),
			(5567,'SS) AccentCare (Texas HHH) - Groesbeck, TX',42339,'AccentCare (Texas HHH) - Groesbeck, TX',197,'AccentCare (Texas HHH)',682,'AccentCare (Texas HHH) - Groesbeck, TX','Location'),
			(5568,'Centric HH & H - Shawnee, OK',null,null,null,null,null,null,null),
			(5569,'Centric HH & H - Greenville, TX',null,null,null,null,null,null,null),
			(5570,'Centric HH & H - Lawton, OK',null,null,null,null,null,null,null),
			(5571,'SS) Affinity - Thomaston (GA)',null,null,null,null,null,null,null),
			(5572,'SS) Affinity - Newnan , GA',42876,'Affinity - Newnan , GA',199,'Affinity Acquisitions Georgia, LLC',689,'Affinity - Newnan , GA','Location'),
			(5573,'SS) Affinity - Columbus , GA',42877,'Affinity - Columbus , GA',199,'Affinity Acquisitions Georgia, LLC',690,'Affinity - Columbus , GA','Location'),
			(5574,'Southern Pines - Houston, TX',null,null,null,null,null,null,null),
			(5575,'Three Oaks - Katy, TX',42861,'Three Oaks - Katy, TX',243,'Three Oaks Hospice, Inc',684,'Three Oaks - Katy, TX','Location'),
			(5576,'SS) Altus - Marble Falls, TX',null,null,null,null,null,null,null),
			(5577,'SS) Amedisys - CCH Beaumont, TX',null,null,null,null,null,null,null),
			(5578,'SS) Traditions - Carrollton, GA',42866,'Traditions - Carrollton, GA',233,'Traditions Hospice (dba)',685,'Traditions - Carrollton, GA','Location'),
			(5579,'SS) Traditions - Lawrenceville, GA',42867,'Traditions - Lawrenceville, GA',233,'Traditions Hospice (dba)',686,'Traditions - Lawrenceville, GA','Location'),
			(5582,'SS) Residential - Lapeer, MI',null,null,null,null,null,null,null),
			(5584,'SS) H2H - Bingham Heights, MI',null,null,null,null,null,null,null),
			(5585,'SS) Georgia HS - Marietta, GA',null,null,null,null,null,null,null),
			(5586,'SS) Affinity - Athens , GA',47611,'Affinity - Athens , GA',199,'Affinity Acquisitions Georgia, LLC',695,'Affinity - Athens , GA','Location'),
			(5587,'Acute HC - Tujunga, CA',null,null,null,null,null,null,null),
			(5588,'SS) Amedisys - Harlingen, TX',47301,'Amedisys - Harlingen, TX',200,'Amedisys, Inc',694,'Amedisys - Harlingen, TX','Location'),
			(5589,'Bristol - Grand Saline, TX',47618,'Bristol - Grand Saline, TX',203,'Bristol Hospice, LLC',697,'Bristol - Grand Saline, TX','Location'),
			(5590,'SS) Traditions - N Norman OK',null,null,null,null,null,null,null),
			(5591,'SS) Holy Savior - Corpus Christi, TX',null,null,null,null,null,null,null),
			(5592,'Like Family - Glendale, CA',null,null,null,null,null,null,null),
			(5593,'A Plus Prime - Pleasanton, CA',null,null,null,null,null,null,null),
			(5595,'Trinity - Chesapeake, VA',null,null,null,null,null,null,null),
			(5596,'Centric HH & H - Durant, OK',null,null,null,null,null,null,null),
			(5597,'Cardinal - Chesapeake, VA',null,null,null,null,null,null,null),
			(5598,'California Mission - Laguna Hills, CA',null,null,null,null,null,null,null),
			(5599,'Aspen H & PC - Round Rock, TX',null,null,null,null,null,null,null),
			(5600,'Green Meadows HC & H - Tustin, CA',null,null,null,null,null,null,null),
			(5601,'Remarkable - El Paso, TX',50659,'Remarkable - El Paso, TX',336,'RHI Management, LLC',701,'Remarkable - El Paso, TX','Location'),		-- For this record netsuite/hmsdigital ids from e2e enviornment one data refresh will update.
			(5602,'Medicalone HH & H - Antioch, CA',null,null,null,null,null,null,null),
			(5603,'M & L Medical Services - Cedar Hills, TX',null,null,null,null,null,null,null),
			(5604,'Qura - El Dorado Hills, CA',null,null,null,null,null,null,null),
			(5605,'Texan Plus - Dallas, TX',null,null,null,null,null,null,null),
			(5606,'Soul - El Monte, CA',null,null,null,null,null,null,null),
			(5607,'Family First - Caddo Mills, TX',null,null,null,null,null,null,null),
			(5608,'Heritage (E TX) - Longview, TX',null,null,null,null,null,null,null),
			(5609,'East Bay - Emeryville, CA',null,null,null,null,null,null,null),
			(5610,'American Guardian HC - Roseville, CA',null,null,null,null,null,null,null),
			(5611,'Haven HC - Simi Valley, CA',null,null,null,null,null,null,null),
			(5612,'Remarkable - Dublin, GA',null,null,null,null,null,null,null),
			(5613,'Bars HC - Van Nuys, CA',null,null,null,null,null,null,null),
			(5614,'SS) Suncrest - Austin, TX',null,null,null,null,null,null,null),
			(5615,'Medvista - Burlingame, CA',null,null,null,null,null,null,null),
			(5616,'SS) Compassus - Clearlake, TX',null,null,null,null,null,null,null),
			(5617,'SS) AccentCare - Denton, TX',null,null,null,null,null,null,null),
			(5618,'SS) Accent Care - Austin, TX ',null,null,null,null,null,null,null),
			(5619,'Silver Age - Pasadena, CA',null,null,null,null,null,null,null),
			(5620,'Trinity - North Chesterfield, VA',null,null,null,null,null,null,null),
			(5621,'Three Oaks - Detroit, MI',null,null,null,null,null,null,null),
			(5622,'Seva - Salida, CA',null,null,null,null,null,null,null),
			(5623,'Remarkable - Plano, TX',null,null,null,null,null,null,null),
			(5624,'SS) Compassus - Orange County, CA',null,null,null,null,null,null,null),
			(5625,'SS) Los Robles Healthcare - Gardena, CA',null,null,null,null,null,null,null),
			(5626,'Trinitycare - Torrance, CA',null,null,null,null,null,null,null),
			(5627,'Healing Care - Downey, CA',null,null,null,null,null,null,null),
			(5628,'Evergreen HC - Cerritos, CA',null,null,null,null,null,null,null),
			(5629,'Global HC - Torrance, CA',null,null,null,null,null,null,null),
			(5630,'Hygieia - Artesia, CA',null,null,null,null,null,null,null),
			(5631,'Santa Ana - Seal Beach, CA',null,null,null,null,null,null,null),
			(5632,'Devina HC - Harbor City, CA',null,null,null,null,null,null,null),
			(5633,'Best Golden Care - Fountain Valley, CA',null,null,null,null,null,null,null),
			(5634,'Warm Care H & P - Garden Grove, CA',null,null,null,null,null,null,null),
			(5635,'Premium - Norwalk, CA',null,null,null,null,null,null,null),
			(5636,'Royal Majesty - Long Beach, CA',null,null,null,null,null,null,null),
			(5637,'Vision Viejo - Mission Viejo, CA',null,null,null,null,null,null,null),
			(5639,'Integrity - Garden Grove, CA',null,null,null,null,null,null,null),
			(5640,'Peregrine - Torrance, CA',null,null,null,null,null,null,null),
			(5641,'Wisteria - Long Beach, CA',null,null,null,null,null,null,null),
			(5642,'Adoration - Chattanooga, TN',null,null,null,null,null,null,null),
			(5643,'Paloma H & PC - Dallas, TX',null,null,null,null,null,null,null),
			(5644,'Angel Wings - Arlington, TX',null,null,null,null,null,null,null),
			(5645,'SS) Compassus - Los Angeles, CA',null,null,null,null,null,null,null),
			(5646,'Trinitycare Kids - Torrance, CA',null,null,null,null,null,null,null),
			(5647,'Trinitycare - Cerritos, CA',null,null,null,null,null,null,null),
			(5648,'Artesia Christian Home - Artesia, CA',null,null,null,null,null,null,null),
			(5649,'Montgomery Marketing - Santa Fe Springs, CA',null,null,null,null,null,null,null),
			(5650,'Seal Beach Rehab - Seal Beach, CA',null,null,null,null,null,null,null),
			(5651,'Rowntree Gardens ',null,null,null,null,null,null,null),
			(5652,'Bel Vista HC - Long Beach, CA',null,null,null,null,null,null,null),
			(5653,'Bixby Knolls Towers - Long Beach, CA',null,null,null,null,null,null,null),
			(5655,'Blue Butterfly - Chatsworth, CA',null,null,null,null,null,null,null),
			(5656,'San Jose - Pharr, TX',null,null,null,null,null,null,null);

UPDATE b SET b.HMS2Name = a.HMS2Name,
			 b.HospiceId = a.DigitalHospiceId,
			 b.HospiceName = a.DigitalHospiceName,
			 b.HospiceLocationId = a.DigitalHospiceLocationId,
			 b.HospiceLocationName = a.DigitalHospiceLocationName,
			 b.NetSuiteCustomerId = a.NetSuiteCustomerId,
			 b.NetSuiteName = a.NetSuiteName,
			 b.DigitalType = a.DigitalType
from @Hms2HmsDigitalList a 
	left join [core].[Hms2HmsDigitalHospiceMappings] b 
	on a.HMS2Id = b.HMS2Id
	where a.NetSuiteCustomerId IS NOT NULL
	   OR a.DigitalHospiceId IS NOT NULL
	   OR a.DigitalHospiceLocationId IS NOT NULL;

INSERT INTO [core].[Hms2HmsDigitalHospiceMappings]              
Select a.HMS2Id, a.HMS2Name, a.NetSuiteCustomerId,a.NetSuiteName, a.DigitalHospiceId,a.DigitalHospiceName,a.DigitalHospiceLocationId,
a.DigitalHospiceLocationName,a.DigitalType
from @Hms2HmsDigitalList a 
	left join [core].[Hms2HmsDigitalHospiceMappings] b 
		on a.HMS2Id = b.HMS2Id and a.HMS2Name = b.HMS2Name
	where b.HMS2Id is null and b.HMS2Name is null;

DELETE FROM [core].[Hms2HmsDigitalHospiceMappings] where HMS2Id in(
Select b.HMS2Id from @Hms2HmsDigitalList a 
	right join [core].[Hms2HmsDigitalHospiceMappings] b 
		on a.HMS2Id = b.HMS2Id 
	where a.HMS2Id is null);

